import 'package:flutter/material.dart';

/// Shared constants for all networking screens.
/// Single source of truth for category data, icons, colors, and filters.
class NetworkingConstants {
  NetworkingConstants._();

  // ── Gender options ──
  static const List<String> genderOptions = [
    'Male',
    'Female',
    'Non-binary',
    'Other',
  ];

  // ── Categories → Subcategories ──
  static const Map<String, List<String>> categorySubcategories = {
    'Professional': [
      'Job Seekers',
      'Recruiters',
      'Freelancers',
      'Consultants',
      'Remote Workers',
      'Career Changers',
      'Interns',
      'Mentors',
      'Resume Review',
      'Interview Prep',
    ],
    'Business': [
      'Startup Founders',
      'Investors',
      'Retailers',
      'Wholesalers',
      'Importers & Exporters',
      'Franchise',
      'E-commerce',
      'B2B Services',
      'Small Business',
      'Partnerships',
    ],
    'Social': [
      'Dating',
      'Friendship',
      'Casual Hangout',
      'Party Buddies',
      'Travel Companions',
      'Roommates',
      'Pen Pals',
      'Neighbors',
      'Nightlife',
      'Coffee Meetups',
    ],
    'Educational': [
      'Tutoring',
      'Study Groups',
      'Online Courses',
      'Skill Exchange',
      'Workshops',
      'Exam Prep',
      'Language Learning',
      'Research',
      'Coding Bootcamp',
      'Certifications',
    ],
    'Creative': [
      'Photography',
      'Graphic Design',
      'Music Production',
      'Film Making',
      'Writing & Blogging',
      'Animation',
      'Fashion Design',
      'Interior Design',
      'Crafts & DIY',
      'Content Creation',
    ],
    'Tech': [
      'Software Development',
      'Web Development',
      'Mobile Apps',
      'AI & Machine Learning',
      'Cybersecurity',
      'Cloud Computing',
      'Data Science',
      'Blockchain',
      'DevOps',
      'UI/UX Design',
    ],
    'Industry': [
      'Manufacturing',
      'Construction',
      'Logistics & Supply Chain',
      'Agriculture',
      'Mining & Energy',
      'Textiles',
      'Automotive',
      'Pharmaceuticals',
      'Food Processing',
      'Real Estate',
    ],
    'Investment & Finance': [
      'Stock Market',
      'Mutual Funds',
      'Real Estate Investment',
      'Cryptocurrency',
      'Insurance',
      'Banking',
      'Fintech',
      'Angel Investing',
      'Venture Capital',
      'Financial Planning',
    ],
    'Event & Meetup': [
      'Conferences',
      'Workshops & Seminars',
      'Hackathons',
      'Networking Events',
      'Cultural Events',
      'Sports Events',
      'Concerts & Music',
      'Webinars',
      'Trade Shows',
      'Community Gatherings',
    ],
    'Community': [
      'NGO & Nonprofits',
      'Volunteering',
      'Social Causes',
      'Environmental',
      'Health Awareness',
      'Education Outreach',
      'Animal Welfare',
      'Elder Care',
      'Women Empowerment',
      'Youth Development',
    ],
    'Personal Development': [
      'Fitness & Gym',
      'Meditation & Yoga',
      'Public Speaking',
      'Leadership Skills',
      'Time Management',
      'Emotional Intelligence',
      'Goal Setting',
      'Mindfulness',
      'Life Coaching',
      'Book Club',
    ],
    'Global / NRI': [
      'Immigration',
      'Visa Assistance',
      'Cultural Exchange',
      'Overseas Jobs',
      'Study Abroad',
      'Diaspora Connect',
      'International Trade',
      'Relocation Help',
      'Foreign Investment',
      'NRI Services',
    ],
  };

  // ── Subcategory colors ──
  static const Map<String, Color> subcategoryColors = {
    // Professional
    'Job Seekers': Color(0xFF3B82F6),
    'Recruiters': Color(0xFF10B981),
    'Freelancers': Color(0xFFF59E0B),
    'Consultants': Color(0xFF8B5CF6),
    'Remote Workers': Color(0xFFEC4899),
    'Career Changers': Color(0xFF14B8A6),
    'Interns': Color(0xFFF97316),
    'Mentors': Color(0xFF06B6D4),
    'Resume Review': Color(0xFFEF4444),
    'Interview Prep': Color(0xFFA855F7),
    // Business
    'Startup Founders': Color(0xFFF97316),
    'Investors': Color(0xFF10B981),
    'Retailers': Color(0xFF3B82F6),
    'Wholesalers': Color(0xFF8B5CF6),
    'Importers & Exporters': Color(0xFF14B8A6),
    'Franchise': Color(0xFFEC4899),
    'E-commerce': Color(0xFFF59E0B),
    'B2B Services': Color(0xFF06B6D4),
    'Small Business': Color(0xFFEF4444),
    'Partnerships': Color(0xFFA855F7),
    // Social
    'Dating': Color(0xFFEF4444),
    'Friendship': Color(0xFF3B82F6),
    'Casual Hangout': Color(0xFFF59E0B),
    'Party Buddies': Color(0xFFA855F7),
    'Travel Companions': Color(0xFF10B981),
    'Roommates': Color(0xFF14B8A6),
    'Pen Pals': Color(0xFFF97316),
    'Neighbors': Color(0xFF8B5CF6),
    'Nightlife': Color(0xFFEC4899),
    'Coffee Meetups': Color(0xFF06B6D4),
    // Educational
    'Tutoring': Color(0xFF3B82F6),
    'Study Groups': Color(0xFF10B981),
    'Online Courses': Color(0xFFEF4444),
    'Skill Exchange': Color(0xFF8B5CF6),
    'Workshops': Color(0xFFF97316),
    'Exam Prep': Color(0xFFEC4899),
    'Language Learning': Color(0xFF14B8A6),
    'Research': Color(0xFF06B6D4),
    'Coding Bootcamp': Color(0xFFA855F7),
    'Certifications': Color(0xFFF59E0B),
    // Creative
    'Photography': Color(0xFF3B82F6),
    'Graphic Design': Color(0xFFF97316),
    'Music Production': Color(0xFFEF4444),
    'Film Making': Color(0xFF10B981),
    'Writing & Blogging': Color(0xFF14B8A6),
    'Animation': Color(0xFFF59E0B),
    'Fashion Design': Color(0xFFEC4899),
    'Interior Design': Color(0xFF8B5CF6),
    'Crafts & DIY': Color(0xFF06B6D4),
    'Content Creation': Color(0xFFA855F7),
    // Tech
    'Software Development': Color(0xFF10B981),
    'Web Development': Color(0xFFF97316),
    'Mobile Apps': Color(0xFF8B5CF6),
    'AI & Machine Learning': Color(0xFFEF4444),
    'Cybersecurity': Color(0xFF14B8A6),
    'Cloud Computing': Color(0xFF06B6D4),
    'Data Science': Color(0xFFF59E0B),
    'Blockchain': Color(0xFFEC4899),
    'DevOps': Color(0xFFA855F7),
    'UI/UX Design': Color(0xFF3B82F6),
    // Industry
    'Manufacturing': Color(0xFF3B82F6),
    'Construction': Color(0xFFF59E0B),
    'Logistics & Supply Chain': Color(0xFF10B981),
    'Agriculture': Color(0xFF14B8A6),
    'Mining & Energy': Color(0xFFEF4444),
    'Textiles': Color(0xFFEC4899),
    'Automotive': Color(0xFF8B5CF6),
    'Pharmaceuticals': Color(0xFF06B6D4),
    'Food Processing': Color(0xFFA855F7),
    'Real Estate': Color(0xFFF97316),
    // Investment & Finance
    'Stock Market': Color(0xFF10B981),
    'Mutual Funds': Color(0xFF3B82F6),
    'Real Estate Investment': Color(0xFFF97316),
    'Cryptocurrency': Color(0xFFF59E0B),
    'Insurance': Color(0xFF8B5CF6),
    'Banking': Color(0xFF14B8A6),
    'Fintech': Color(0xFFEF4444),
    'Angel Investing': Color(0xFFEC4899),
    'Venture Capital': Color(0xFFA855F7),
    'Financial Planning': Color(0xFF06B6D4),
    // Event & Meetup
    'Conferences': Color(0xFF3B82F6),
    'Workshops & Seminars': Color(0xFFF59E0B),
    'Hackathons': Color(0xFF10B981),
    'Networking Events': Color(0xFF8B5CF6),
    'Cultural Events': Color(0xFFEC4899),
    'Sports Events': Color(0xFFF97316),
    'Concerts & Music': Color(0xFFA855F7),
    'Webinars': Color(0xFF14B8A6),
    'Trade Shows': Color(0xFF06B6D4),
    'Community Gatherings': Color(0xFFEF4444),
    // Community
    'NGO & Nonprofits': Color(0xFF10B981),
    'Volunteering': Color(0xFF3B82F6),
    'Social Causes': Color(0xFFEF4444),
    'Environmental': Color(0xFF14B8A6),
    'Health Awareness': Color(0xFFF97316),
    'Education Outreach': Color(0xFFF59E0B),
    'Animal Welfare': Color(0xFFEC4899),
    'Elder Care': Color(0xFF8B5CF6),
    'Women Empowerment': Color(0xFFA855F7),
    'Youth Development': Color(0xFF06B6D4),
    // Personal Development
    'Fitness & Gym': Color(0xFFEF4444),
    'Meditation & Yoga': Color(0xFF10B981),
    'Public Speaking': Color(0xFF3B82F6),
    'Leadership Skills': Color(0xFFF59E0B),
    'Time Management': Color(0xFFF97316),
    'Emotional Intelligence': Color(0xFF8B5CF6),
    'Goal Setting': Color(0xFF14B8A6),
    'Mindfulness': Color(0xFFEC4899),
    'Life Coaching': Color(0xFFA855F7),
    'Book Club': Color(0xFF06B6D4),
    // Global / NRI
    'Immigration': Color(0xFF3B82F6),
    'Visa Assistance': Color(0xFF10B981),
    'Cultural Exchange': Color(0xFFEC4899),
    'Overseas Jobs': Color(0xFFF97316),
    'Study Abroad': Color(0xFFF59E0B),
    'Diaspora Connect': Color(0xFF8B5CF6),
    'International Trade': Color(0xFF14B8A6),
    'Relocation Help': Color(0xFFEF4444),
    'Foreign Investment': Color(0xFFA855F7),
    'NRI Services': Color(0xFF06B6D4),
  };

  // ── Category icons (rounded) ──
  static const Map<String, IconData> categoryIcons = {
    'Professional': Icons.business_center_rounded,
    'Business': Icons.storefront_rounded,
    'Social': Icons.groups_rounded,
    'Educational': Icons.school_rounded,
    'Creative': Icons.palette_rounded,
    'Tech': Icons.computer_rounded,
    'Industry': Icons.factory_rounded,
    'Investment & Finance': Icons.account_balance_rounded,
    'Event & Meetup': Icons.event_rounded,
    'Community': Icons.volunteer_activism_rounded,
    'Personal Development': Icons.self_improvement_rounded,
    'Global / NRI': Icons.public_rounded,
  };

  // ── Subcategory icons ──
  static const Map<String, IconData> subcategoryIcons = {
    // Professional
    'Job Seekers': Icons.person_search_rounded,
    'Recruiters': Icons.badge_rounded,
    'Freelancers': Icons.laptop_mac_rounded,
    'Consultants': Icons.support_agent_rounded,
    'Remote Workers': Icons.home_work_rounded,
    'Career Changers': Icons.swap_horiz_rounded,
    'Interns': Icons.school_rounded,
    'Mentors': Icons.psychology_rounded,
    'Resume Review': Icons.description_rounded,
    'Interview Prep': Icons.record_voice_over_rounded,
    // Business
    'Startup Founders': Icons.rocket_launch_rounded,
    'Investors': Icons.trending_up_rounded,
    'Retailers': Icons.store_rounded,
    'Wholesalers': Icons.warehouse_rounded,
    'Importers & Exporters': Icons.local_shipping_rounded,
    'Franchise': Icons.business_rounded,
    'E-commerce': Icons.shopping_cart_rounded,
    'B2B Services': Icons.handshake_rounded,
    'Small Business': Icons.storefront_rounded,
    'Partnerships': Icons.group_work_rounded,
    // Social
    'Dating': Icons.favorite_rounded,
    'Friendship': Icons.people_rounded,
    'Casual Hangout': Icons.local_cafe_rounded,
    'Party Buddies': Icons.celebration_rounded,
    'Travel Companions': Icons.flight_rounded,
    'Roommates': Icons.house_rounded,
    'Pen Pals': Icons.mail_rounded,
    'Neighbors': Icons.location_city_rounded,
    'Nightlife': Icons.nightlife_rounded,
    'Coffee Meetups': Icons.coffee_rounded,
    // Educational
    'Tutoring': Icons.menu_book_rounded,
    'Study Groups': Icons.groups_rounded,
    'Online Courses': Icons.ondemand_video_rounded,
    'Skill Exchange': Icons.swap_calls_rounded,
    'Workshops': Icons.build_rounded,
    'Exam Prep': Icons.quiz_rounded,
    'Language Learning': Icons.translate_rounded,
    'Research': Icons.biotech_rounded,
    'Coding Bootcamp': Icons.code_rounded,
    'Certifications': Icons.verified_rounded,
    // Creative
    'Photography': Icons.camera_alt_rounded,
    'Graphic Design': Icons.design_services_rounded,
    'Music Production': Icons.music_note_rounded,
    'Film Making': Icons.videocam_rounded,
    'Writing & Blogging': Icons.edit_note_rounded,
    'Animation': Icons.animation_rounded,
    'Fashion Design': Icons.checkroom_rounded,
    'Interior Design': Icons.chair_rounded,
    'Crafts & DIY': Icons.handyman_rounded,
    'Content Creation': Icons.create_rounded,
    // Tech
    'Software Development': Icons.terminal_rounded,
    'Web Development': Icons.web_rounded,
    'Mobile Apps': Icons.phone_android_rounded,
    'AI & Machine Learning': Icons.smart_toy_rounded,
    'Cybersecurity': Icons.security_rounded,
    'Cloud Computing': Icons.cloud_rounded,
    'Data Science': Icons.analytics_rounded,
    'Blockchain': Icons.link_rounded,
    'DevOps': Icons.settings_suggest_rounded,
    'UI/UX Design': Icons.brush_rounded,
    // Industry
    'Manufacturing': Icons.precision_manufacturing_rounded,
    'Construction': Icons.construction_rounded,
    'Logistics & Supply Chain': Icons.local_shipping_rounded,
    'Agriculture': Icons.grass_rounded,
    'Mining & Energy': Icons.bolt_rounded,
    'Textiles': Icons.checkroom_rounded,
    'Automotive': Icons.directions_car_rounded,
    'Pharmaceuticals': Icons.medication_rounded,
    'Food Processing': Icons.restaurant_rounded,
    'Real Estate': Icons.apartment_rounded,
    // Investment & Finance
    'Stock Market': Icons.candlestick_chart_rounded,
    'Mutual Funds': Icons.pie_chart_rounded,
    'Real Estate Investment': Icons.home_work_rounded,
    'Cryptocurrency': Icons.currency_bitcoin_rounded,
    'Insurance': Icons.shield_rounded,
    'Banking': Icons.account_balance_rounded,
    'Fintech': Icons.payments_rounded,
    'Angel Investing': Icons.star_rounded,
    'Venture Capital': Icons.rocket_rounded,
    'Financial Planning': Icons.savings_rounded,
    // Event & Meetup
    'Conferences': Icons.mic_rounded,
    'Workshops & Seminars': Icons.co_present_rounded,
    'Hackathons': Icons.code_rounded,
    'Networking Events': Icons.hub_rounded,
    'Cultural Events': Icons.theater_comedy_rounded,
    'Sports Events': Icons.sports_rounded,
    'Concerts & Music': Icons.library_music_rounded,
    'Webinars': Icons.cast_rounded,
    'Trade Shows': Icons.storefront_rounded,
    'Community Gatherings': Icons.diversity_3_rounded,
    // Community
    'NGO & Nonprofits': Icons.volunteer_activism_rounded,
    'Volunteering': Icons.handshake_rounded,
    'Social Causes': Icons.campaign_rounded,
    'Environmental': Icons.eco_rounded,
    'Health Awareness': Icons.health_and_safety_rounded,
    'Education Outreach': Icons.school_rounded,
    'Animal Welfare': Icons.pets_rounded,
    'Elder Care': Icons.elderly_rounded,
    'Women Empowerment': Icons.woman_rounded,
    'Youth Development': Icons.child_care_rounded,
    // Personal Development
    'Fitness & Gym': Icons.fitness_center_rounded,
    'Meditation & Yoga': Icons.self_improvement_rounded,
    'Public Speaking': Icons.record_voice_over_rounded,
    'Leadership Skills': Icons.military_tech_rounded,
    'Time Management': Icons.schedule_rounded,
    'Emotional Intelligence': Icons.psychology_alt_rounded,
    'Goal Setting': Icons.flag_rounded,
    'Mindfulness': Icons.spa_rounded,
    'Life Coaching': Icons.emoji_people_rounded,
    'Book Club': Icons.auto_stories_rounded,
    // Global / NRI
    'Immigration': Icons.flight_land_rounded,
    'Visa Assistance': Icons.card_travel_rounded,
    'Cultural Exchange': Icons.diversity_1_rounded,
    'Overseas Jobs': Icons.work_rounded,
    'Study Abroad': Icons.school_rounded,
    'Diaspora Connect': Icons.connect_without_contact_rounded,
    'International Trade': Icons.public_rounded,
    'Relocation Help': Icons.moving_rounded,
    'Foreign Investment': Icons.monetization_on_rounded,
    'NRI Services': Icons.support_rounded,
  };

  // ── Category gradient colors (for profile badges, cards) ──
  static const Map<String, List<Color>> categoryColors = {
    'Professional': [Color(0xFF6366F1), Color(0xFF818CF8)],
    'Business': [Color(0xFF10B981), Color(0xFF34D399)],
    'Social': [Color(0xFFEC4899), Color(0xFFF472B6)],
    'Educational': [Color(0xFFF59E0B), Color(0xFFFBBF24)],
    'Creative': [Color(0xFFA855F7), Color(0xFFC084FC)],
    'Tech': [Color(0xFF3B82F6), Color(0xFF60A5FA)],
    'Industry': [Color(0xFFF97316), Color(0xFFFB923C)],
    'Investment & Finance': [Color(0xFF14B8A6), Color(0xFF2DD4BF)],
    'Event & Meetup': [Color(0xFFEF4444), Color(0xFFF87171)],
    'Community': [Color(0xFF8B5CF6), Color(0xFFA78BFA)],
    'Personal Development': [Color(0xFF06B6D4), Color(0xFF22D3EE)],
    'Global / NRI': [Color(0xFFD946EF), Color(0xFFE879F9)],
  };

  // ── Flat icons (non-rounded, used in Live Connect tab chips) ──
  static const Map<String, IconData> categoryFlatIcons = {
    'Professional': Icons.business_center,
    'Business': Icons.storefront,
    'Social': Icons.groups,
    'Educational': Icons.school,
    'Creative': Icons.palette,
    'Tech': Icons.computer,
    'Industry': Icons.factory,
    'Investment & Finance': Icons.account_balance,
    'Event & Meetup': Icons.event,
    'Community': Icons.volunteer_activism,
    'Personal Development': Icons.self_improvement,
    'Global / NRI': Icons.public,
  };

  // ── Flat colors (single color, used in Live Connect tab chips) ──
  static const Map<String, Color> categoryFlatColors = {
    'Professional': Color(0xFF2196F3),
    'Business': Color(0xFFFFA502),
    'Social': Color(0xFF00D2D3),
    'Educational': Color(0xFFFF6348),
    'Creative': Color(0xFFFF9100),
    'Tech': Color(0xFF7C4DFF),
    'Industry': Color(0xFF78909C),
    'Investment & Finance': Color(0xFF4CAF50),
    'Event & Meetup': Color(0xFFE040FB),
    'Community': Color(0xFFFF6B81),
    'Personal Development': Color(0xFF00E676),
    'Global / NRI': Color(0xFF1E90FF),
  };

  // ── Category → connection type groups (Live Connect) ──
  static const Map<String, List<String>> categoryConnectionGroups = {
    'Professional': [],
    'Business': [],
    'Social': ['Social', 'Other'],
    'Educational': ['Educational'],
    'Creative': ['Creative'],
    'Tech': [],
    'Industry': [],
    'Investment & Finance': [],
    'Event & Meetup': [],
    'Community': ['Community'],
    'Personal Development': [],
    'Global / NRI': [],
  };

  // ── Category → activity groups (Live Connect) ──
  static const Map<String, List<String>> categoryActivityGroups = {
    'Professional': [],
    'Business': [],
    'Social': ['Sports', 'Fitness', 'Outdoor', 'Creative'],
    'Educational': ['Creative'],
    'Creative': ['Creative'],
    'Tech': [],
    'Industry': [],
    'Investment & Finance': [],
    'Event & Meetup': ['Sports', 'Creative'],
    'Community': ['Sports', 'Outdoor'],
    'Personal Development': ['Fitness', 'Outdoor'],
    'Global / NRI': [],
  };

  // ── Category-specific filters ──
  static const Map<String, List<Map<String, dynamic>>> categoryFilters = {
    'Professional': [
      {
        'label': 'Experience Level',
        'type': 'dropdown',
        'options': [
          'Entry Level',
          'Mid Level',
          'Senior',
          'Executive',
          'Intern',
        ],
      },
      {
        'label': 'Employment Type',
        'type': 'dropdown',
        'options': [
          'Full-Time',
          'Part-Time',
          'Contract',
          'Freelance',
          'Internship',
        ],
      },
      {
        'label': 'Work Mode',
        'type': 'dropdown',
        'options': ['On-Site', 'Remote', 'Hybrid'],
      },
      {
        'label': 'Industry',
        'type': 'dropdown',
        'options': [
          'Technology',
          'Healthcare',
          'Finance',
          'Education',
          'Marketing',
          'Legal',
          'Manufacturing',
          'Retail',
          'Media',
          'Government',
          'Other',
        ],
      },
    ],
    'Business': [
      {
        'label': 'Business Stage',
        'type': 'dropdown',
        'options': [
          'Idea Stage',
          'Pre-Revenue',
          'Early Revenue',
          'Growth Stage',
          'Established',
          'Scaling',
        ],
      },
      {
        'label': 'Company Size',
        'type': 'dropdown',
        'options': ['Solo', '2-10', '11-50', '51-200', '201-1000', '1000+'],
      },
      {
        'label': 'Business Model',
        'type': 'dropdown',
        'options': ['B2B', 'B2C', 'D2C', 'Marketplace', 'SaaS', 'Subscription'],
      },
      {
        'label': 'Industry Sector',
        'type': 'dropdown',
        'options': [
          'Technology',
          'Retail',
          'F&B',
          'Healthcare',
          'Manufacturing',
          'Real Estate',
          'Agriculture',
          'Services',
          'Logistics',
          'Finance',
          'Other',
        ],
      },
    ],
    'Social': [
      {
        'label': 'Availability',
        'type': 'dropdown',
        'options': ['Now', 'Today', 'This Week', 'This Weekend', 'Flexible'],
      },
      {
        'label': 'Interests',
        'type': 'dropdown',
        'options': [
          'Music',
          'Sports',
          'Travel',
          'Food',
          'Art',
          'Tech',
          'Fitness',
          'Reading',
          'Gaming',
          'Movies',
          'Photography',
          'Cooking',
        ],
      },
      {
        'label': 'Vibe',
        'type': 'dropdown',
        'options': [
          'Chill',
          'Energetic',
          'Intellectual',
          'Creative',
          'Adventurous',
        ],
      },
    ],
    'Educational': [
      {
        'label': 'Skill Level',
        'type': 'dropdown',
        'options': ['Beginner', 'Intermediate', 'Advanced', 'Expert'],
      },
      {
        'label': 'Format',
        'type': 'dropdown',
        'options': ['In-Person', 'Online Live', 'Self-Paced', 'Hybrid'],
      },
      {
        'label': 'Subject',
        'type': 'dropdown',
        'options': [
          'Mathematics',
          'Science',
          'Languages',
          'Programming',
          'Business',
          'Arts',
          'Music',
          'Test Prep',
          'Other',
        ],
      },
      {
        'label': 'Language',
        'type': 'dropdown',
        'options': [
          'English',
          'Hindi',
          'Spanish',
          'French',
          'Mandarin',
          'Arabic',
          'German',
          'Japanese',
          'Other',
        ],
      },
    ],
    'Creative': [
      {
        'label': 'Skill Level',
        'type': 'dropdown',
        'options': [
          'Hobbyist',
          'Beginner',
          'Intermediate',
          'Professional',
          'Expert',
        ],
      },
      {
        'label': 'Collaboration',
        'type': 'dropdown',
        'options': [
          'Hire Me',
          'Looking to Hire',
          'Collaborate',
          'Learn Together',
          'Mentor/Mentee',
        ],
      },
      {
        'label': 'Portfolio',
        'type': 'dropdown',
        'options': ['Has Portfolio', 'No Portfolio'],
      },
    ],
    'Tech': [
      {
        'label': 'Experience Level',
        'type': 'dropdown',
        'options': [
          'Junior (0-2 yr)',
          'Mid (2-5 yr)',
          'Senior (5-10 yr)',
          'Lead/Architect (10+ yr)',
        ],
      },
      {
        'label': 'Tech Stack',
        'type': 'dropdown',
        'options': [
          'Python',
          'JavaScript',
          'TypeScript',
          'Java',
          'C++',
          'Go',
          'Rust',
          'Swift',
          'Kotlin',
          'Dart',
          'Flutter',
          'React',
        ],
      },
      {
        'label': 'Purpose',
        'type': 'dropdown',
        'options': [
          'Hire',
          'Get Hired',
          'Collaborate',
          'Learn',
          'Mentor',
          'Open Source',
        ],
      },
    ],
    'Industry': [
      {
        'label': 'Business Role',
        'type': 'dropdown',
        'options': [
          'Manufacturer',
          'Supplier',
          'Distributor',
          'Buyer',
          'Consultant',
          'Service Provider',
        ],
      },
      {
        'label': 'Company Size',
        'type': 'dropdown',
        'options': [
          'Micro (1-10)',
          'Small (11-50)',
          'Medium (51-200)',
          'Large (201-1000)',
          'Enterprise (1000+)',
        ],
      },
      {
        'label': 'Trade Type',
        'type': 'dropdown',
        'options': ['Local', 'National', 'International'],
      },
      {
        'label': 'Certifications',
        'type': 'dropdown',
        'options': [
          'ISO 9001',
          'ISO 14001',
          'GMP',
          'HACCP',
          'CE',
          'FDA',
          'BIS',
          'Organic',
        ],
      },
    ],
    'Investment & Finance': [
      {
        'label': 'Experience',
        'type': 'dropdown',
        'options': ['Beginner', 'Intermediate', 'Advanced', 'Professional'],
      },
      {
        'label': 'Risk Appetite',
        'type': 'dropdown',
        'options': [
          'Conservative',
          'Moderate',
          'Aggressive',
          'Very Aggressive',
        ],
      },
      {
        'label': 'Investment Horizon',
        'type': 'dropdown',
        'options': [
          'Short-Term (< 1yr)',
          'Medium (1-3yr)',
          'Long-Term (3-10yr)',
          'Very Long (10+yr)',
        ],
      },
      {
        'label': 'Purpose',
        'type': 'dropdown',
        'options': ['Invest', 'Raise Capital', 'Advise', 'Learn', 'Partner'],
      },
    ],
    'Event & Meetup': [
      {
        'label': 'Event Format',
        'type': 'dropdown',
        'options': ['In-Person', 'Online', 'Hybrid'],
      },
      {
        'label': 'When',
        'type': 'dropdown',
        'options': ['Today', 'This Week', 'This Weekend', 'This Month'],
      },
      {
        'label': 'Time of Day',
        'type': 'dropdown',
        'options': ['Morning', 'Afternoon', 'Evening', 'Night'],
      },
      {
        'label': 'Price',
        'type': 'dropdown',
        'options': ['Free', 'Paid'],
      },
    ],
    'Community': [
      {
        'label': 'Involvement',
        'type': 'dropdown',
        'options': ['Volunteer', 'Donate', 'Organize', 'Advocate', 'Mentor'],
      },
      {
        'label': 'Commitment',
        'type': 'dropdown',
        'options': ['One-Time', 'Weekly', 'Monthly', 'Ongoing', 'Seasonal'],
      },
      {
        'label': 'Cause Area',
        'type': 'dropdown',
        'options': [
          'Education',
          'Health',
          'Environment',
          'Poverty',
          'Human Rights',
          'Animals',
          'Arts & Culture',
          'Technology',
        ],
      },
      {
        'label': 'Skills Offered',
        'type': 'dropdown',
        'options': [
          'Teaching',
          'Medical',
          'Technical',
          'Legal',
          'Marketing',
          'Fundraising',
          'Counseling',
          'Creative',
        ],
      },
    ],
    'Personal Development': [
      {
        'label': 'Level',
        'type': 'dropdown',
        'options': ['Beginner', 'Intermediate', 'Advanced'],
      },
      {
        'label': 'Format',
        'type': 'dropdown',
        'options': [
          'In-Person',
          'Online Live',
          'Self-Paced',
          'Group',
          '1-on-1',
        ],
      },
      {
        'label': 'Session Duration',
        'type': 'dropdown',
        'options': ['15 min', '30 min', '45 min', '1 hr', '2 hr'],
      },
      {
        'label': 'Goal',
        'type': 'dropdown',
        'options': [
          'Weight Loss',
          'Muscle Gain',
          'Flexibility',
          'Stress Relief',
          'Focus',
          'Confidence',
          'Leadership',
        ],
      },
    ],
    'Global / NRI': [
      {
        'label': 'Destination',
        'type': 'dropdown',
        'options': [
          'USA',
          'Canada',
          'UK',
          'Australia',
          'Germany',
          'UAE',
          'Singapore',
          'New Zealand',
          'Other',
        ],
      },
      {
        'label': 'Service Type',
        'type': 'dropdown',
        'options': [
          'Consultation',
          'Documentation',
          'Representation',
          'Guidance',
          'Community',
        ],
      },
      {
        'label': 'Urgency',
        'type': 'dropdown',
        'options': [
          'Immediate',
          'Within 1 Month',
          'Within 3 Months',
          'Within 6 Months',
          'Planning Ahead',
        ],
      },
      {
        'label': 'Language',
        'type': 'dropdown',
        'options': [
          'English',
          'Hindi',
          'Gujarati',
          'Punjabi',
          'Tamil',
          'Telugu',
          'Bengali',
          'Marathi',
        ],
      },
    ],
  };

  // ── Filter Option Icons ──
  static const Map<String, IconData> filterOptionIcons = {
    // Education
    'High School': Icons.school_rounded,
    'Associate': Icons.menu_book_rounded,
    'Bachelor\'s': Icons.history_edu_rounded,
    'Master\'s': Icons.workspace_premium_rounded,
    'PhD': Icons.emoji_events_rounded,
    'Self-Taught': Icons.auto_stories_rounded,
    // Project Type
    'Hourly': Icons.schedule_rounded,
    'Fixed-Price': Icons.attach_money_rounded,
    'Retainer': Icons.handshake_rounded,
    'Equity': Icons.pie_chart_rounded,
    // Specialty / Consultants
    'Strategy': Icons.lightbulb_rounded,
    'Operations': Icons.settings_rounded,
    'Finance': Icons.account_balance_rounded,
    'Marketing': Icons.campaign_rounded,
    'HR': Icons.people_rounded,
    'IT': Icons.computer_rounded,
    'Legal': Icons.gavel_rounded,
    // Time Zone
    'IST (UTC+5:30)': Icons.flag_rounded,
    'EST (UTC-5)': Icons.public_rounded,
    'PST (UTC-8)': Icons.wb_sunny_rounded,
    'GMT (UTC+0)': Icons.schedule_rounded,
    'CET (UTC+1)': Icons.euro_rounded,
    'AEST (UTC+10)': Icons.south_rounded,
    'JST (UTC+9)': Icons.temple_buddhist_rounded,
    // Hiring For
    'Tech': Icons.code_rounded,
    'Sales': Icons.point_of_sale_rounded,
    'Design': Icons.palette_rounded,
    'Executive': Icons.business_center_rounded,
    // Funding Stage
    'Bootstrapped': Icons.rocket_launch_rounded,
    'Pre-Seed': Icons.eco_rounded,
    'Seed': Icons.spa_rounded,
    'Series A': Icons.looks_one_rounded,
    'Series B': Icons.looks_two_rounded,
    'Series C+': Icons.looks_3_rounded,
    'Growth': Icons.trending_up_rounded,
    // Investment Type
    'Angel': Icons.favorite_rounded,
    'VC': Icons.monetization_on_rounded,
    'PE': Icons.corporate_fare_rounded,
    'Debt': Icons.receipt_long_rounded,
    'Crypto': Icons.currency_bitcoin_rounded,
    // Platforms
    'Shopify': Icons.store_rounded,
    'Amazon': Icons.local_shipping_rounded,
    'WooCommerce': Icons.shopping_cart_rounded,
    'Custom': Icons.build_rounded,
    'Multi-Platform': Icons.devices_rounded,
    // Franchise Type
    'Food': Icons.restaurant_rounded,
    'Retail': Icons.storefront_rounded,
    'Service': Icons.miscellaneous_services_rounded,
    'Education': Icons.school_rounded,
    'Fitness': Icons.fitness_center_rounded,
    // Relationship Goal
    'Serious': Icons.favorite_rounded,
    'Casual': Icons.emoji_emotions_rounded,
    'Open to Anything': Icons.all_inclusive_rounded,
    // Lifestyle
    'Non-Smoker': Icons.smoke_free_rounded,
    'Social Drinker': Icons.local_bar_rounded,
    'Vegetarian': Icons.eco_rounded,
    'Fitness Lover': Icons.fitness_center_rounded,
    'Pet Lover': Icons.pets_rounded,
    'Early Bird': Icons.wb_sunny_rounded,
    'Night Owl': Icons.dark_mode_rounded,
    'Pet-Friendly': Icons.pets_rounded,
    'Quiet': Icons.volume_off_rounded,
    // Travel
    'Budget': Icons.savings_rounded,
    'Mid-Range': Icons.hotel_rounded,
    'Luxury': Icons.diamond_rounded,
    'Backpacking': Icons.hiking_rounded,
    'Weekend': Icons.weekend_rounded,
    '1 Week': Icons.date_range_rounded,
    '2+ Weeks': Icons.calendar_month_rounded,
    'Long-Term': Icons.flight_rounded,
    // Party
    'Clubs': Icons.nightlife_rounded,
    'Bars': Icons.local_bar_rounded,
    'House Parties': Icons.house_rounded,
    'Live Music': Icons.music_note_rounded,
    'Rooftops': Icons.roofing_rounded,
    // Music Taste / Genre
    'EDM': Icons.graphic_eq_rounded,
    'Hip-Hop': Icons.mic_rounded,
    'Bollywood': Icons.movie_rounded,
    'Rock': Icons.electric_bolt_rounded,
    'Pop': Icons.star_rounded,
    'Jazz': Icons.piano_rounded,
    'Classical': Icons.library_music_rounded,
    'Lo-Fi': Icons.headphones_rounded,
    'Indie': Icons.music_note_rounded,
    // Exams
    'SAT': Icons.quiz_rounded,
    'GRE': Icons.school_rounded,
    'GMAT': Icons.calculate_rounded,
    'IELTS': Icons.language_rounded,
    'TOEFL': Icons.translate_rounded,
    'UPSC': Icons.account_balance_rounded,
    'CAT': Icons.business_rounded,
    'JEE': Icons.engineering_rounded,
    'NEET': Icons.medical_services_rounded,
    // Languages
    'English': Icons.abc_rounded,
    'Spanish': Icons.flag_rounded,
    'French': Icons.flag_rounded,
    'German': Icons.flag_rounded,
    'Mandarin': Icons.translate_rounded,
    'Japanese': Icons.translate_rounded,
    'Korean': Icons.translate_rounded,
    'Arabic': Icons.translate_rounded,
    'Hindi': Icons.translate_rounded,
    // Proficiency
    'A1 (Beginner)': Icons.looks_one_rounded,
    'A2 (Elementary)': Icons.looks_two_rounded,
    'B1 (Intermediate)': Icons.looks_3_rounded,
    'B2 (Upper Intermediate)': Icons.looks_4_rounded,
    'C1 (Advanced)': Icons.looks_5_rounded,
    'C2 (Fluent)': Icons.verified_rounded,
    // Tech Stack
    'Python': Icons.code_rounded,
    'JavaScript': Icons.javascript_rounded,
    'React': Icons.web_rounded,
    'Node.js': Icons.dns_rounded,
    'Flutter': Icons.flutter_dash_rounded,
    'AI/ML': Icons.psychology_rounded,
    'Java': Icons.coffee_rounded,
    'Swift': Icons.apple_rounded,
    // Duration
    '4 Weeks': Icons.date_range_rounded,
    '8 Weeks': Icons.calendar_month_rounded,
    '12 Weeks': Icons.calendar_today_rounded,
    '6 Months': Icons.event_rounded,
    // Group Size
    '2-3': Icons.people_rounded,
    '4-6': Icons.groups_rounded,
    '7-10': Icons.groups_3_rounded,
    '10+': Icons.diversity_3_rounded,
    // Photography Style
    'Portrait': Icons.face_rounded,
    'Landscape': Icons.landscape_rounded,
    'Wedding': Icons.favorite_rounded,
    'Product': Icons.inventory_2_rounded,
    'Street': Icons.streetview_rounded,
    'Fashion': Icons.checkroom_rounded,
    'Drone': Icons.flight_rounded,
    // Graphic Design
    'Logo': Icons.brush_rounded,
    'Branding': Icons.branding_watermark_rounded,
    'UI/UX': Icons.design_services_rounded,
    'Print': Icons.print_rounded,
    'Packaging': Icons.inventory_rounded,
    'Social Media': Icons.share_rounded,
    'Illustration': Icons.draw_rounded,
    // Music Service
    'Mixing': Icons.tune_rounded,
    'Mastering': Icons.equalizer_rounded,
    'Beat Making': Icons.queue_music_rounded,
    'Composition': Icons.edit_note_rounded,
    'Sound Design': Icons.surround_sound_rounded,
    // Film Type
    'Short Film': Icons.movie_creation_rounded,
    'Documentary': Icons.videocam_rounded,
    'Commercial': Icons.live_tv_rounded,
    'Music Video': Icons.music_video_rounded,
    'Corporate': Icons.business_rounded,
    // Film Roles
    'Director': Icons.movie_filter_rounded,
    'Editor': Icons.content_cut_rounded,
    'Cinematographer': Icons.camera_rounded,
    'Actor': Icons.theater_comedy_rounded,
    'Sound': Icons.spatial_audio_rounded,
    'VFX': Icons.auto_awesome_rounded,
    // Content Platforms
    'YouTube': Icons.play_circle_rounded,
    'Instagram': Icons.camera_alt_rounded,
    'TikTok': Icons.video_library_rounded,
    'Podcast': Icons.podcasts_rounded,
    'Blog': Icons.article_rounded,
    'LinkedIn': Icons.work_rounded,
    // Content Type
    'Video': Icons.videocam_rounded,
    'Photo': Icons.photo_camera_rounded,
    'Written': Icons.edit_rounded,
    'Audio': Icons.audiotrack_rounded,
    'Mixed Media': Icons.perm_media_rounded,
    // Writing Niche
    'Lifestyle': Icons.self_improvement_rounded,
    'Travel': Icons.flight_rounded,
    'Health': Icons.health_and_safety_rounded,
    'Fiction': Icons.auto_stories_rounded,
    'Copywriting': Icons.text_snippet_rounded,
    // Software Domain
    'Backend': Icons.storage_rounded,
    'Frontend': Icons.web_rounded,
    'Full-Stack': Icons.layers_rounded,
    'Embedded': Icons.memory_rounded,
    'Systems': Icons.developer_board_rounded,
    // Mobile Platform
    'iOS': Icons.phone_iphone_rounded,
    'Android': Icons.phone_android_rounded,
    'Cross-Platform': Icons.devices_rounded,
    'React Native': Icons.code_rounded,
    // AI Subfield
    'NLP': Icons.text_fields_rounded,
    'Computer Vision': Icons.visibility_rounded,
    'Deep Learning': Icons.hub_rounded,
    'Generative AI': Icons.auto_awesome_rounded,
    'MLOps': Icons.precision_manufacturing_rounded,
    'Reinforcement Learning': Icons.psychology_alt_rounded,
    // Cybersecurity
    'Pen Testing': Icons.security_rounded,
    'Security Audit': Icons.verified_user_rounded,
    'Compliance': Icons.fact_check_rounded,
    'Incident Response': Icons.warning_rounded,
    'SOC': Icons.shield_rounded,
    'GRC': Icons.policy_rounded,
    // Cloud
    'AWS': Icons.cloud_rounded,
    'Azure': Icons.cloud_circle_rounded,
    'GCP': Icons.cloud_queue_rounded,
    'Multi-Cloud': Icons.cloud_sync_rounded,
    // Data Science Tools
    'R': Icons.functions_rounded,
    'SQL': Icons.table_chart_rounded,
    'Tableau': Icons.bar_chart_rounded,
    'Power BI': Icons.analytics_rounded,
    'Spark': Icons.bolt_rounded,
    // Blockchain Chains
    'Ethereum': Icons.hexagon_rounded,
    'Solana': Icons.speed_rounded,
    'Bitcoin': Icons.currency_bitcoin_rounded,
    'Polygon': Icons.change_history_rounded,
    'Polkadot': Icons.blur_on_rounded,
    // Blockchain Focus
    'Smart Contracts': Icons.description_rounded,
    'DeFi': Icons.account_balance_wallet_rounded,
    'NFT': Icons.token_rounded,
    'DApp': Icons.apps_rounded,
    'Web3': Icons.language_rounded,
    // UI/UX Tools
    'Figma': Icons.design_services_rounded,
    'Sketch': Icons.gesture_rounded,
    'Adobe XD': Icons.grid_view_rounded,
    'Framer': Icons.animation_rounded,
    'InVision': Icons.preview_rounded,
    // Manufacturing
    'Small Batch': Icons.inventory_rounded,
    'Medium': Icons.warehouse_rounded,
    'Large Scale': Icons.factory_rounded,
    'Mass Production': Icons.precision_manufacturing_rounded,
    // Construction
    'Residential': Icons.home_rounded,
    'Infrastructure': Icons.construction_rounded,
    'Industrial': Icons.factory_rounded,
    'Renovation': Icons.home_repair_service_rounded,
    // Real Estate
    'Land': Icons.terrain_rounded,
    'Co-Working': Icons.meeting_room_rounded,
    'Buy': Icons.shopping_bag_rounded,
    'Sell': Icons.sell_rounded,
    'Rent': Icons.vpn_key_rounded,
    'Lease': Icons.assignment_rounded,
    // Agriculture
    'Crops': Icons.grass_rounded,
    'Livestock': Icons.pets_rounded,
    'Dairy': Icons.water_drop_rounded,
    'Poultry': Icons.egg_rounded,
    'Aquaculture': Icons.water_rounded,
    'Organic': Icons.eco_rounded,
    'AgriTech': Icons.biotech_rounded,
    // Automotive
    'Passenger': Icons.directions_car_rounded,
    'Two-Wheeler': Icons.two_wheeler_rounded,
    'EV': Icons.electric_car_rounded,
    'Parts': Icons.build_rounded,
    // Pharma
    'Generic': Icons.medication_rounded,
    'Branded': Icons.local_pharmacy_rounded,
    'API': Icons.science_rounded,
    'Biotech': Icons.biotech_rounded,
    'Medical Devices': Icons.medical_services_rounded,
    // Food Processing
    'Bakery': Icons.bakery_dining_rounded,
    'Beverages': Icons.local_drink_rounded,
    'Frozen': Icons.ac_unit_rounded,
    'Snacks': Icons.fastfood_rounded,
    'Spices': Icons.local_fire_department_rounded,
    // Stock Market Sector
    'Technology': Icons.computer_rounded,
    'Healthcare': Icons.local_hospital_rounded,
    'Energy': Icons.bolt_rounded,
    'Consumer': Icons.shopping_bag_rounded,
    'Real Estate': Icons.apartment_rounded,
    // Market Cap
    'Micro': Icons.looks_one_rounded,
    'Small': Icons.looks_two_rounded,
    'Mid': Icons.looks_3_rounded,
    'Large': Icons.looks_4_rounded,
    'Mega': Icons.looks_5_rounded,
    // Token Type
    'Layer 1': Icons.foundation_rounded,
    'Layer 2': Icons.layers_rounded,
    'Stablecoin': Icons.attach_money_rounded,
    'Meme': Icons.emoji_emotions_rounded,
    // Fund Type
    'Hybrid': Icons.merge_rounded,
    'Index': Icons.show_chart_rounded,
    'ELSS': Icons.savings_rounded,
    'Liquid': Icons.water_drop_rounded,
    // Sectors
    'FinTech': Icons.account_balance_rounded,
    'EdTech': Icons.school_rounded,
    'D2C': Icons.store_rounded,
    'SaaS': Icons.cloud_rounded,
    // Goals
    'Retirement': Icons.elderly_rounded,
    'Wealth Building': Icons.trending_up_rounded,
    'Tax Saving': Icons.receipt_rounded,
    'Emergency Fund': Icons.shield_rounded,
    'Debt Payoff': Icons.money_off_rounded,
    // Hackathon
    'AI': Icons.smart_toy_rounded,
    'Social Good': Icons.volunteer_activism_rounded,
    'Open': Icons.lock_open_rounded,
    // Team Size
    'Solo': Icons.person_rounded,
    '4-5': Icons.group_rounded,
    // Audience
    'Beginner': Icons.school_rounded,
    'Professional': Icons.work_rounded,
    'Academic': Icons.science_rounded,
    // Sports
    'Cricket': Icons.sports_cricket_rounded,
    'Football': Icons.sports_soccer_rounded,
    'Tennis': Icons.sports_tennis_rounded,
    'Running': Icons.directions_run_rounded,
    'Cycling': Icons.directions_bike_rounded,
    'Swimming': Icons.pool_rounded,
    'Martial Arts': Icons.sports_martial_arts_rounded,
    // Participation
    'Participate': Icons.emoji_events_rounded,
    'Spectate': Icons.visibility_rounded,
    'Volunteer': Icons.volunteer_activism_rounded,
    // Availability
    'Weekdays': Icons.work_rounded,
    'Weekends': Icons.weekend_rounded,
    'Evenings': Icons.nights_stay_rounded,
    'Flexible': Icons.all_inclusive_rounded,
    // Environment
    'Climate': Icons.thermostat_rounded,
    'Conservation': Icons.park_rounded,
    'Recycling': Icons.recycling_rounded,
    'Clean Energy': Icons.solar_power_rounded,
    'Water': Icons.water_drop_rounded,
    'Reforestation': Icons.forest_rounded,
    'Wildlife': Icons.cruelty_free_rounded,
    // Animal Type
    'Dogs': Icons.pets_rounded,
    'Cats': Icons.pets_rounded,
    'Farm Animals': Icons.agriculture_rounded,
    'Marine': Icons.sailing_rounded,
    'Birds': Icons.flutter_dash_rounded,
    'All': Icons.diversity_3_rounded,
    // Women Empowerment Focus
    'Employment': Icons.work_rounded,
    'Safety': Icons.security_rounded,
    'Legal Rights': Icons.gavel_rounded,
    'Leadership': Icons.leaderboard_rounded,
    'Financial': Icons.account_balance_wallet_rounded,
    // Age Group
    '6-10': Icons.child_care_rounded,
    '11-14': Icons.boy_rounded,
    '15-18': Icons.school_rounded,
    '18-25': Icons.person_rounded,
    // Program Type
    'Sports': Icons.sports_rounded,
    'STEM': Icons.biotech_rounded,
    'Arts': Icons.palette_rounded,
    'Career': Icons.work_rounded,
    'Life Skills': Icons.psychology_rounded,
    // Workout Type
    'Strength': Icons.fitness_center_rounded,
    'Cardio': Icons.monitor_heart_rounded,
    'CrossFit': Icons.sports_gymnastics_rounded,
    'HIIT': Icons.timer_rounded,
    'Calisthenics': Icons.sports_gymnastics_rounded,
    'Functional': Icons.accessibility_new_rounded,
    // Fitness Goal
    'Weight Loss': Icons.monitor_weight_rounded,
    'Muscle Gain': Icons.fitness_center_rounded,
    'Endurance': Icons.directions_run_rounded,
    'Flexibility': Icons.self_improvement_rounded,
    'General Fitness': Icons.favorite_rounded,
    // Yoga Style
    'Hatha': Icons.self_improvement_rounded,
    'Vinyasa': Icons.air_rounded,
    'Ashtanga': Icons.sports_gymnastics_rounded,
    'Kundalini': Icons.local_fire_department_rounded,
    'Guided Meditation': Icons.spa_rounded,
    'Breathwork': Icons.air_rounded,
    // Speaking Context
    'TED-Style': Icons.mic_rounded,
    'Debate': Icons.forum_rounded,
    'Toastmasters': Icons.record_voice_over_rounded,
    'Storytelling': Icons.auto_stories_rounded,
    // Coaching Specialty
    'Relationships': Icons.people_rounded,
    'Confidence': Icons.psychology_rounded,
    // Book Genre
    'Self-Help': Icons.self_improvement_rounded,
    'Business': Icons.business_rounded,
    'Science': Icons.science_rounded,
    'Philosophy': Icons.lightbulb_rounded,
    'Biography': Icons.person_rounded,
    'Psychology': Icons.psychology_rounded,
    // Book Pace
    '1 Chapter/Week': Icons.menu_book_rounded,
    'Whole Book': Icons.book_rounded,
    'Audio + Discussion': Icons.headphones_rounded,
    // Visa
    'Work Visa': Icons.work_rounded,
    'Family Visa': Icons.family_restroom_rounded,
    'Investor Visa': Icons.attach_money_rounded,
    'Permanent Residence': Icons.home_rounded,
    'Citizenship': Icons.card_membership_rounded,
    'Asylum': Icons.shield_rounded,
    // Degree Level
    'Undergraduate': Icons.school_rounded,
    'Postgraduate': Icons.workspace_premium_rounded,
    'Diploma': Icons.card_membership_rounded,
    'Certificate': Icons.verified_rounded,
    'Short Course': Icons.schedule_rounded,
    // Intake
    'Fall': Icons.park_rounded,
    'Spring': Icons.local_florist_rounded,
    'Summer': Icons.wb_sunny_rounded,
    'Rolling': Icons.loop_rounded,
    // Contract Type
    'Permanent': Icons.work_rounded,
    'Contract': Icons.description_rounded,
    'Temporary': Icons.timer_rounded,
    'Sponsorship Available': Icons.card_giftcard_rounded,
    // Trade Direction
    'Import': Icons.call_received_rounded,
    'Export': Icons.call_made_rounded,
    'Both': Icons.swap_horiz_rounded,
    // Volume
    'Bulk': Icons.local_shipping_rounded,
    // Relocation Service
    'Housing': Icons.home_rounded,
    'Banking': Icons.account_balance_rounded,
    'Schools': Icons.school_rounded,
    'Moving': Icons.local_shipping_rounded,
    // NRI Services
    'Tax Filing': Icons.receipt_long_rounded,
    'Property Management': Icons.apartment_rounded,
    'Power of Attorney': Icons.gavel_rounded,
    'Bank Account': Icons.account_balance_rounded,
    'Insurance': Icons.health_and_safety_rounded,
    'Repatriation': Icons.flight_land_rounded,
    // Gender
    'Male': Icons.male_rounded,
    'Female': Icons.female_rounded,
    'Non-binary': Icons.transgender_rounded,
    'Other': Icons.more_horiz_rounded,
    // ── Category Filter Options ──
    // Experience Level
    'Entry Level': Icons.star_border_rounded,
    'Mid Level': Icons.star_half_rounded,
    'Senior': Icons.star_rounded,
    'Intern': Icons.school_rounded,
    // Employment Type
    'Full-Time': Icons.work_rounded,
    'Part-Time': Icons.work_outline_rounded,
    'Freelance': Icons.laptop_mac_rounded,
    'Internship': Icons.school_rounded,
    // Work Mode
    'On-Site': Icons.apartment_rounded,
    'Remote': Icons.home_work_rounded,
    // Industry (extra)
    'Media': Icons.newspaper_rounded,
    'Government': Icons.account_balance_rounded,
    // Business Stage
    'Idea Stage': Icons.lightbulb_outline_rounded,
    'Pre-Revenue': Icons.trending_flat_rounded,
    'Early Revenue': Icons.trending_up_rounded,
    'Growth Stage': Icons.rocket_launch_rounded,
    'Established': Icons.verified_rounded,
    'Scaling': Icons.expand_rounded,
    // Company Size
    '2-10': Icons.people_rounded,
    '11-50': Icons.groups_rounded,
    '51-200': Icons.groups_3_rounded,
    '201-1000': Icons.corporate_fare_rounded,
    '1000+': Icons.domain_rounded,
    // Business Model
    'B2B': Icons.handshake_rounded,
    'B2C': Icons.storefront_rounded,
    'Marketplace': Icons.store_rounded,
    'Subscription': Icons.autorenew_rounded,
    // Industry Sector (extra)
    'F&B': Icons.restaurant_rounded,
    'Services': Icons.miscellaneous_services_rounded,
    'Logistics': Icons.local_shipping_rounded,
    // Social Availability
    'Now': Icons.access_time_rounded,
    'Today': Icons.today_rounded,
    'This Week': Icons.date_range_rounded,
    'This Weekend': Icons.weekend_rounded,
    // Social Interests
    'Music': Icons.music_note_rounded,
    'Art': Icons.palette_rounded,
    'Reading': Icons.menu_book_rounded,
    'Gaming': Icons.sports_esports_rounded,
    'Movies': Icons.movie_rounded,
    'Cooking': Icons.restaurant_menu_rounded,
    // Vibes
    'Chill': Icons.spa_rounded,
    'Energetic': Icons.bolt_rounded,
    'Intellectual': Icons.psychology_rounded,
    'Adventurous': Icons.explore_rounded,
    // Educational Formats
    'In-Person': Icons.person_rounded,
    'Online Live': Icons.videocam_rounded,
    'Self-Paced': Icons.schedule_rounded,
    // Educational Subjects
    'Mathematics': Icons.calculate_rounded,
    'Languages': Icons.translate_rounded,
    'Programming': Icons.code_rounded,
    'Test Prep': Icons.quiz_rounded,
    // Skill Level (extra)
    'Intermediate': Icons.trending_up_rounded,
    'Advanced': Icons.military_tech_rounded,
    'Expert': Icons.emoji_events_rounded,
    // Creative Collaboration
    'Hobbyist': Icons.palette_rounded,
    'Hire Me': Icons.person_add_rounded,
    'Looking to Hire': Icons.person_search_rounded,
    'Collaborate': Icons.handshake_rounded,
    'Learn Together': Icons.school_rounded,
    'Mentor/Mentee': Icons.supervisor_account_rounded,
    'Has Portfolio': Icons.folder_rounded,
    'No Portfolio': Icons.folder_off_rounded,
    // Tech Experience Level
    'Junior (0-2 yr)': Icons.star_border_rounded,
    'Mid (2-5 yr)': Icons.star_half_rounded,
    'Senior (5-10 yr)': Icons.star_rounded,
    'Lead/Architect (10+ yr)': Icons.architecture_rounded,
    // Tech Stack (extra)
    'TypeScript': Icons.code_rounded,
    'C++': Icons.memory_rounded,
    'Go': Icons.speed_rounded,
    'Rust': Icons.settings_rounded,
    'Kotlin': Icons.phone_android_rounded,
    'Dart': Icons.flutter_dash_rounded,
    // Tech Purpose
    'Hire': Icons.person_add_rounded,
    'Get Hired': Icons.badge_rounded,
    'Learn': Icons.school_rounded,
    'Mentor': Icons.supervisor_account_rounded,
    'Open Source': Icons.public_rounded,
    // Industry Roles
    'Manufacturer': Icons.factory_rounded,
    'Supplier': Icons.inventory_rounded,
    'Distributor': Icons.local_shipping_rounded,
    'Buyer': Icons.shopping_cart_rounded,
    'Consultant': Icons.support_agent_rounded,
    'Service Provider': Icons.build_rounded,
    // Industry Company Size
    'Micro (1-10)': Icons.person_rounded,
    'Small (11-50)': Icons.people_rounded,
    'Medium (51-200)': Icons.groups_rounded,
    'Large (201-1000)': Icons.corporate_fare_rounded,
    'Enterprise (1000+)': Icons.domain_rounded,
    // Trade Type
    'Local': Icons.location_on_rounded,
    'National': Icons.flag_rounded,
    'International': Icons.public_rounded,
    // Certifications
    'ISO 9001': Icons.verified_rounded,
    'ISO 14001': Icons.eco_rounded,
    'GMP': Icons.verified_user_rounded,
    'HACCP': Icons.food_bank_rounded,
    'CE': Icons.check_circle_rounded,
    'FDA': Icons.medical_services_rounded,
    'BIS': Icons.shield_rounded,
    // Risk Appetite
    'Conservative': Icons.shield_rounded,
    'Moderate': Icons.balance_rounded,
    'Aggressive': Icons.trending_up_rounded,
    'Very Aggressive': Icons.rocket_launch_rounded,
    // Investment Horizon
    'Short-Term (< 1yr)': Icons.timer_rounded,
    'Medium (1-3yr)': Icons.hourglass_bottom_rounded,
    'Long-Term (3-10yr)': Icons.hourglass_full_rounded,
    'Very Long (10+yr)': Icons.all_inclusive_rounded,
    // Investment Purpose
    'Invest': Icons.attach_money_rounded,
    'Raise Capital': Icons.trending_up_rounded,
    'Advise': Icons.support_agent_rounded,
    'Partner': Icons.handshake_rounded,
    // Event Format
    'Online': Icons.videocam_rounded,
    // Event When
    'This Month': Icons.calendar_month_rounded,
    // Time of Day
    'Morning': Icons.wb_sunny_rounded,
    'Afternoon': Icons.wb_cloudy_rounded,
    'Evening': Icons.nights_stay_rounded,
    'Night': Icons.dark_mode_rounded,
    // Event Price
    'Free': Icons.money_off_rounded,
    'Paid': Icons.attach_money_rounded,
    // Community Involvement
    'Donate': Icons.volunteer_activism_rounded,
    'Organize': Icons.event_rounded,
    'Advocate': Icons.campaign_rounded,
    // Commitment
    'One-Time': Icons.looks_one_rounded,
    'Weekly': Icons.date_range_rounded,
    'Monthly': Icons.calendar_month_rounded,
    'Ongoing': Icons.loop_rounded,
    'Seasonal': Icons.park_rounded,
    // Cause Area
    'Environment': Icons.eco_rounded,
    'Poverty': Icons.volunteer_activism_rounded,
    'Human Rights': Icons.gavel_rounded,
    'Animals': Icons.pets_rounded,
    'Arts & Culture': Icons.palette_rounded,
    // Skills Offered
    'Teaching': Icons.school_rounded,
    'Medical': Icons.medical_services_rounded,
    'Technical': Icons.build_rounded,
    'Fundraising': Icons.attach_money_rounded,
    'Counseling': Icons.psychology_rounded,
    'Creative': Icons.brush_rounded,
    // Personal Development Format
    'Group': Icons.groups_rounded,
    '1-on-1': Icons.person_rounded,
    // Session Duration
    '15 min': Icons.timer_rounded,
    '30 min': Icons.timer_rounded,
    '45 min': Icons.timer_rounded,
    '1 hr': Icons.schedule_rounded,
    '2 hr': Icons.schedule_rounded,
    // Goals (extra)
    'Stress Relief': Icons.spa_rounded,
    'Focus': Icons.center_focus_strong_rounded,
    // Global Destinations
    'USA': Icons.flag_rounded,
    'Canada': Icons.flag_rounded,
    'UK': Icons.flag_rounded,
    'Australia': Icons.flag_rounded,
    'Germany': Icons.flag_rounded,
    'UAE': Icons.flag_rounded,
    'Singapore': Icons.flag_rounded,
    'New Zealand': Icons.flag_rounded,
    // Service Type
    'Consultation': Icons.support_agent_rounded,
    'Documentation': Icons.description_rounded,
    'Representation': Icons.person_rounded,
    'Guidance': Icons.assistant_rounded,
    'Community': Icons.groups_rounded,
    // Urgency
    'Immediate': Icons.priority_high_rounded,
    'Within 1 Month': Icons.date_range_rounded,
    'Within 3 Months': Icons.calendar_month_rounded,
    'Within 6 Months': Icons.calendar_today_rounded,
    'Planning Ahead': Icons.event_rounded,
    // Indian Languages
    'Gujarati': Icons.translate_rounded,
    'Punjabi': Icons.translate_rounded,
    'Tamil': Icons.translate_rounded,
    'Telugu': Icons.translate_rounded,
    'Bengali': Icons.translate_rounded,
    'Marathi': Icons.translate_rounded,
  };

  // ── Filter Option Colors ──
  static const Map<String, Color> filterOptionColors = {
    // Education
    'High School': Color(0xFF3B82F6),
    'Associate': Color(0xFF6366F1),
    'Bachelor\'s': Color(0xFF8B5CF6),
    'Master\'s': Color(0xFFA855F7),
    'PhD': Color(0xFFD946EF),
    'Self-Taught': Color(0xFF14B8A6),
    // Project Type
    'Hourly': Color(0xFF0EA5E9),
    'Fixed-Price': Color(0xFF10B981),
    'Retainer': Color(0xFF6366F1),
    'Equity': Color(0xFFF59E0B),
    // Consultants
    'Strategy': Color(0xFF8B5CF6),
    'Operations': Color(0xFF64748B),
    'Finance': Color(0xFF10B981),
    'Marketing': Color(0xFFEC4899),
    'HR': Color(0xFF06B6D4),
    'IT': Color(0xFF3B82F6),
    'Legal': Color(0xFF78716C),
    // Time Zones
    'IST (UTC+5:30)': Color(0xFFFF6B35),
    'EST (UTC-5)': Color(0xFF3B82F6),
    'PST (UTC-8)': Color(0xFFF59E0B),
    'GMT (UTC+0)': Color(0xFF10B981),
    'CET (UTC+1)': Color(0xFF6366F1),
    'AEST (UTC+10)': Color(0xFF14B8A6),
    'JST (UTC+9)': Color(0xFFEF4444),
    // Hiring For
    'Tech': Color(0xFF3B82F6),
    'Sales': Color(0xFF10B981),
    'Design': Color(0xFFEC4899),
    'Executive': Color(0xFF1E293B),
    // Funding Stage
    'Bootstrapped': Color(0xFFEF4444),
    'Pre-Seed': Color(0xFF22C55E),
    'Seed': Color(0xFF84CC16),
    'Series A': Color(0xFF3B82F6),
    'Series B': Color(0xFF6366F1),
    'Series C+': Color(0xFF8B5CF6),
    'Growth': Color(0xFF14B8A6),
    // Investment Type
    'Angel': Color(0xFFF472B6),
    'VC': Color(0xFF6366F1),
    'PE': Color(0xFF1E293B),
    'Debt': Color(0xFF78716C),
    'Crypto': Color(0xFFF59E0B),
    // Platforms
    'Shopify': Color(0xFF96BF48),
    'Amazon': Color(0xFFFF9900),
    'WooCommerce': Color(0xFF7B5EA7),
    'Custom': Color(0xFF64748B),
    'Multi-Platform': Color(0xFF3B82F6),
    // Franchise Type
    'Food': Color(0xFFEF4444),
    'Retail': Color(0xFF6366F1),
    'Service': Color(0xFF0EA5E9),
    'Education': Color(0xFF8B5CF6),
    'Fitness': Color(0xFF22C55E),
    // Relationship
    'Serious': Color(0xFFEF4444),
    'Casual': Color(0xFFF59E0B),
    'Open to Anything': Color(0xFF8B5CF6),
    // Lifestyle
    'Non-Smoker': Color(0xFF22C55E),
    'Social Drinker': Color(0xFFF59E0B),
    'Vegetarian': Color(0xFF10B981),
    'Fitness Lover': Color(0xFFEF4444),
    'Pet Lover': Color(0xFFEC4899),
    'Early Bird': Color(0xFFFBBF24),
    'Night Owl': Color(0xFF6366F1),
    'Pet-Friendly': Color(0xFFF472B6),
    'Quiet': Color(0xFF94A3B8),
    // Travel
    'Budget': Color(0xFF22C55E),
    'Mid-Range': Color(0xFF3B82F6),
    'Luxury': Color(0xFFD4AF37),
    'Backpacking': Color(0xFF14B8A6),
    'Weekend': Color(0xFF0EA5E9),
    '1 Week': Color(0xFF6366F1),
    '2+ Weeks': Color(0xFF8B5CF6),
    'Long-Term': Color(0xFFEC4899),
    // Party
    'Clubs': Color(0xFF8B5CF6),
    'Bars': Color(0xFFF59E0B),
    'House Parties': Color(0xFFEC4899),
    'Live Music': Color(0xFFEF4444),
    'Rooftops': Color(0xFF0EA5E9),
    // Music / Genre
    'EDM': Color(0xFF8B5CF6),
    'Hip-Hop': Color(0xFFEF4444),
    'Bollywood': Color(0xFFFF6B35),
    'Rock': Color(0xFF1E293B),
    'Pop': Color(0xFFEC4899),
    'Jazz': Color(0xFFF59E0B),
    'Classical': Color(0xFF78716C),
    'Lo-Fi': Color(0xFF14B8A6),
    'Indie': Color(0xFF22C55E),
    // Exams
    'SAT': Color(0xFF3B82F6),
    'GRE': Color(0xFF6366F1),
    'GMAT': Color(0xFF0EA5E9),
    'IELTS': Color(0xFFEF4444),
    'TOEFL': Color(0xFF10B981),
    'UPSC': Color(0xFFFF6B35),
    'CAT': Color(0xFF8B5CF6),
    'JEE': Color(0xFF14B8A6),
    'NEET': Color(0xFF22C55E),
    // Languages
    'English': Color(0xFF3B82F6),
    'Spanish': Color(0xFFEF4444),
    'French': Color(0xFF6366F1),
    'German': Color(0xFF1E293B),
    'Mandarin': Color(0xFFEF4444),
    'Japanese': Color(0xFFEF4444),
    'Korean': Color(0xFF0EA5E9),
    'Arabic': Color(0xFF10B981),
    'Hindi': Color(0xFFFF6B35),
    // Proficiency
    'A1 (Beginner)': Color(0xFFEF4444),
    'A2 (Elementary)': Color(0xFFF59E0B),
    'B1 (Intermediate)': Color(0xFF3B82F6),
    'B2 (Upper Intermediate)': Color(0xFF6366F1),
    'C1 (Advanced)': Color(0xFF8B5CF6),
    'C2 (Fluent)': Color(0xFF22C55E),
    // Tech Stack
    'Python': Color(0xFF3776AB),
    'JavaScript': Color(0xFFF7DF1E),
    'React': Color(0xFF61DAFB),
    'Node.js': Color(0xFF339933),
    'Flutter': Color(0xFF02569B),
    'AI/ML': Color(0xFF8B5CF6),
    'Java': Color(0xFFED8B00),
    'Swift': Color(0xFFFA7343),
    // Duration
    '4 Weeks': Color(0xFF22C55E),
    '8 Weeks': Color(0xFF3B82F6),
    '12 Weeks': Color(0xFF6366F1),
    '6 Months': Color(0xFF8B5CF6),
    // Group Size
    '2-3': Color(0xFF0EA5E9),
    '4-6': Color(0xFF6366F1),
    '7-10': Color(0xFF8B5CF6),
    '10+': Color(0xFFEC4899),
    // Photography Style
    'Portrait': Color(0xFFEC4899),
    'Landscape': Color(0xFF22C55E),
    'Wedding': Color(0xFFF472B6),
    'Product': Color(0xFF3B82F6),
    'Street': Color(0xFF64748B),
    'Fashion': Color(0xFFD946EF),
    'Drone': Color(0xFF0EA5E9),
    // Graphic Design
    'Logo': Color(0xFFF59E0B),
    'Branding': Color(0xFFEC4899),
    'UI/UX': Color(0xFF6366F1),
    'Print': Color(0xFF78716C),
    'Packaging': Color(0xFF14B8A6),
    'Social Media': Color(0xFF3B82F6),
    'Illustration': Color(0xFFA855F7),
    // Music Service
    'Mixing': Color(0xFF3B82F6),
    'Mastering': Color(0xFF6366F1),
    'Beat Making': Color(0xFFEF4444),
    'Composition': Color(0xFF8B5CF6),
    'Sound Design': Color(0xFF14B8A6),
    // Film Type
    'Short Film': Color(0xFF6366F1),
    'Documentary': Color(0xFF78716C),
    'Commercial': Color(0xFF3B82F6),
    'Music Video': Color(0xFFEC4899),
    'Corporate': Color(0xFF1E293B),
    // Film Roles
    'Director': Color(0xFFEF4444),
    'Editor': Color(0xFF6366F1),
    'Cinematographer': Color(0xFF0EA5E9),
    'Actor': Color(0xFFF59E0B),
    'Sound': Color(0xFF14B8A6),
    'VFX': Color(0xFF8B5CF6),
    // Content Platforms
    'YouTube': Color(0xFFFF0000),
    'Instagram': Color(0xFFE4405F),
    'TikTok': Color(0xFF000000),
    'Podcast': Color(0xFF8B5CF6),
    'Blog': Color(0xFF3B82F6),
    'LinkedIn': Color(0xFF0A66C2),
    // Content Type
    'Video': Color(0xFFEF4444),
    'Photo': Color(0xFF3B82F6),
    'Written': Color(0xFF6366F1),
    'Audio': Color(0xFF14B8A6),
    'Mixed Media': Color(0xFFEC4899),
    // Writing Niche
    'Lifestyle': Color(0xFFEC4899),
    'Travel': Color(0xFF0EA5E9),
    'Health': Color(0xFF22C55E),
    'Fiction': Color(0xFF8B5CF6),
    'Copywriting': Color(0xFFF59E0B),
    // Software Domain
    'Backend': Color(0xFF3B82F6),
    'Frontend': Color(0xFF22C55E),
    'Full-Stack': Color(0xFF6366F1),
    'Embedded': Color(0xFF78716C),
    'Systems': Color(0xFFEF4444),
    // Mobile Platform
    'iOS': Color(0xFF007AFF),
    'Android': Color(0xFF3DDC84),
    'Cross-Platform': Color(0xFF6366F1),
    'React Native': Color(0xFF61DAFB),
    // AI Subfield
    'NLP': Color(0xFF3B82F6),
    'Computer Vision': Color(0xFF22C55E),
    'Deep Learning': Color(0xFF8B5CF6),
    'Generative AI': Color(0xFFEC4899),
    'MLOps': Color(0xFF64748B),
    'Reinforcement Learning': Color(0xFFF59E0B),
    // Cybersecurity
    'Pen Testing': Color(0xFFEF4444),
    'Security Audit': Color(0xFF3B82F6),
    'Compliance': Color(0xFF6366F1),
    'Incident Response': Color(0xFFF59E0B),
    'SOC': Color(0xFF14B8A6),
    'GRC': Color(0xFF78716C),
    // Cloud
    'AWS': Color(0xFFFF9900),
    'Azure': Color(0xFF0078D4),
    'GCP': Color(0xFF4285F4),
    'Multi-Cloud': Color(0xFF6366F1),
    // Data Science
    'R': Color(0xFF276DC3),
    'SQL': Color(0xFFE48E00),
    'Tableau': Color(0xFF4E79A7),
    'Power BI': Color(0xFFF2C811),
    'Spark': Color(0xFFE25A1C),
    // Blockchain
    'Ethereum': Color(0xFF627EEA),
    'Solana': Color(0xFF00FFA3),
    'Bitcoin': Color(0xFFF7931A),
    'Polygon': Color(0xFF8247E5),
    'Polkadot': Color(0xFFE6007A),
    'Smart Contracts': Color(0xFF627EEA),
    'DeFi': Color(0xFF22C55E),
    'NFT': Color(0xFFEC4899),
    'DApp': Color(0xFF8B5CF6),
    'Web3': Color(0xFF3B82F6),
    // UI/UX Tools
    'Figma': Color(0xFFF24E1E),
    'Sketch': Color(0xFFFDB300),
    'Adobe XD': Color(0xFFFF61F6),
    'Framer': Color(0xFF0055FF),
    'InVision': Color(0xFFFF3366),
    // Manufacturing
    'Small Batch': Color(0xFF22C55E),
    'Medium': Color(0xFF3B82F6),
    'Large Scale': Color(0xFF6366F1),
    'Mass Production': Color(0xFF8B5CF6),
    // Construction
    'Residential': Color(0xFF3B82F6),
    'Infrastructure': Color(0xFF64748B),
    'Industrial': Color(0xFF78716C),
    'Renovation': Color(0xFFF59E0B),
    // Real Estate
    'Land': Color(0xFF22C55E),
    'Co-Working': Color(0xFF6366F1),
    'Buy': Color(0xFF3B82F6),
    'Sell': Color(0xFFEF4444),
    'Rent': Color(0xFFF59E0B),
    'Lease': Color(0xFF14B8A6),
    // Agriculture
    'Crops': Color(0xFF22C55E),
    'Livestock': Color(0xFF78716C),
    'Dairy': Color(0xFF0EA5E9),
    'Poultry': Color(0xFFF59E0B),
    'Aquaculture': Color(0xFF14B8A6),
    'Organic': Color(0xFF84CC16),
    'AgriTech': Color(0xFF3B82F6),
    // Automotive
    'Passenger': Color(0xFF3B82F6),
    'Two-Wheeler': Color(0xFFF59E0B),
    'EV': Color(0xFF22C55E),
    'Parts': Color(0xFF64748B),
    // Pharma
    'Generic': Color(0xFF3B82F6),
    'Branded': Color(0xFF8B5CF6),
    'API': Color(0xFF14B8A6),
    'Biotech': Color(0xFFEC4899),
    'Medical Devices': Color(0xFF0EA5E9),
    // Food Processing
    'Bakery': Color(0xFFF59E0B),
    'Beverages': Color(0xFF0EA5E9),
    'Frozen': Color(0xFF06B6D4),
    'Snacks': Color(0xFFEF4444),
    'Spices': Color(0xFFFF6B35),
    // Stock Sectors
    'Technology': Color(0xFF3B82F6),
    'Healthcare': Color(0xFF22C55E),
    'Energy': Color(0xFFF59E0B),
    'Consumer': Color(0xFFEC4899),
    'Real Estate': Color(0xFF6366F1),
    // Market Cap
    'Micro': Color(0xFF22C55E),
    'Small': Color(0xFF3B82F6),
    'Mid': Color(0xFF6366F1),
    'Large': Color(0xFF8B5CF6),
    'Mega': Color(0xFFD946EF),
    // Token Type
    'Layer 1': Color(0xFF3B82F6),
    'Layer 2': Color(0xFF6366F1),
    'Stablecoin': Color(0xFF22C55E),
    'Meme': Color(0xFFF59E0B),
    // Fund Type
    'Hybrid': Color(0xFF6366F1),
    'Index': Color(0xFF14B8A6),
    'ELSS': Color(0xFF22C55E),
    'Liquid': Color(0xFF0EA5E9),
    // Preferred Sectors
    'FinTech': Color(0xFF10B981),
    'EdTech': Color(0xFF8B5CF6),
    'D2C': Color(0xFFEC4899),
    'SaaS': Color(0xFF3B82F6),
    // Financial Goals
    'Retirement': Color(0xFF6366F1),
    'Wealth Building': Color(0xFFF59E0B),
    'Tax Saving': Color(0xFF22C55E),
    'Emergency Fund': Color(0xFFEF4444),
    'Debt Payoff': Color(0xFF78716C),
    // Hackathon
    'AI': Color(0xFF8B5CF6),
    'Social Good': Color(0xFF22C55E),
    'Open': Color(0xFF3B82F6),
    'HealthTech': Color(0xFFEF4444),
    // Team Size
    'Solo': Color(0xFF6366F1),
    '4-5': Color(0xFF8B5CF6),
    // Audience
    'Beginner': Color(0xFF22C55E),
    'Professional': Color(0xFF3B82F6),
    'Academic': Color(0xFF8B5CF6),
    // Sports
    'Cricket': Color(0xFF22C55E),
    'Football': Color(0xFF3B82F6),
    'Tennis': Color(0xFFF59E0B),
    'Running': Color(0xFFEF4444),
    'Cycling': Color(0xFF0EA5E9),
    'Swimming': Color(0xFF06B6D4),
    'Martial Arts': Color(0xFF1E293B),
    // Participation
    'Participate': Color(0xFF22C55E),
    'Spectate': Color(0xFF3B82F6),
    'Volunteer': Color(0xFFEC4899),
    // Availability
    'Weekdays': Color(0xFF3B82F6),
    'Weekends': Color(0xFF22C55E),
    'Evenings': Color(0xFF6366F1),
    'Flexible': Color(0xFF14B8A6),
    // Environment Focus
    'Climate': Color(0xFFEF4444),
    'Conservation': Color(0xFF22C55E),
    'Recycling': Color(0xFF14B8A6),
    'Clean Energy': Color(0xFFF59E0B),
    'Water': Color(0xFF0EA5E9),
    'Reforestation': Color(0xFF16A34A),
    'Wildlife': Color(0xFF78716C),
    // Animals
    'Dogs': Color(0xFFF59E0B),
    'Cats': Color(0xFF8B5CF6),
    'Farm Animals': Color(0xFF78716C),
    'Marine': Color(0xFF0EA5E9),
    'Birds': Color(0xFF22C55E),
    'All': Color(0xFF3B82F6),
    // Women Empowerment
    'Employment': Color(0xFF3B82F6),
    'Safety': Color(0xFFEF4444),
    'Legal Rights': Color(0xFF6366F1),
    'Leadership': Color(0xFF8B5CF6),
    'Financial': Color(0xFF10B981),
    // Age Group
    '6-10': Color(0xFF22C55E),
    '11-14': Color(0xFF3B82F6),
    '15-18': Color(0xFF6366F1),
    '18-25': Color(0xFF8B5CF6),
    // Program Type
    'Sports': Color(0xFFEF4444),
    'STEM': Color(0xFF3B82F6),
    'Arts': Color(0xFFA855F7),
    'Career': Color(0xFF6366F1),
    'Life Skills': Color(0xFF14B8A6),
    // Workout
    'Strength': Color(0xFFEF4444),
    'Cardio': Color(0xFF22C55E),
    'CrossFit': Color(0xFFF59E0B),
    'HIIT': Color(0xFFEC4899),
    'Calisthenics': Color(0xFF6366F1),
    'Functional': Color(0xFF0EA5E9),
    // Fitness Goal
    'Weight Loss': Color(0xFF22C55E),
    'Muscle Gain': Color(0xFFEF4444),
    'Endurance': Color(0xFF3B82F6),
    'Flexibility': Color(0xFF8B5CF6),
    'General Fitness': Color(0xFF14B8A6),
    // Yoga
    'Hatha': Color(0xFF6366F1),
    'Vinyasa': Color(0xFF0EA5E9),
    'Ashtanga': Color(0xFFEF4444),
    'Kundalini': Color(0xFFF59E0B),
    'Guided Meditation': Color(0xFF8B5CF6),
    'Breathwork': Color(0xFF14B8A6),
    // Speaking
    'TED-Style': Color(0xFFEF4444),
    'Debate': Color(0xFF3B82F6),
    'Toastmasters': Color(0xFF6366F1),
    'Storytelling': Color(0xFFF59E0B),
    // Coaching
    'Relationships': Color(0xFFEC4899),
    'Confidence': Color(0xFF8B5CF6),
    // Book Genre
    'Self-Help': Color(0xFF22C55E),
    'Business': Color(0xFF3B82F6),
    'Science': Color(0xFF6366F1),
    'Philosophy': Color(0xFFF59E0B),
    'Biography': Color(0xFF78716C),
    'Psychology': Color(0xFF8B5CF6),
    // Pace
    '1 Chapter/Week': Color(0xFF3B82F6),
    'Whole Book': Color(0xFFEF4444),
    'Audio + Discussion': Color(0xFF6366F1),
    // Visa
    'Work Visa': Color(0xFF3B82F6),
    'Family Visa': Color(0xFFEC4899),
    'Investor Visa': Color(0xFF10B981),
    'Permanent Residence': Color(0xFF6366F1),
    'Citizenship': Color(0xFFF59E0B),
    'Asylum': Color(0xFF78716C),
    // Degree
    'Undergraduate': Color(0xFF3B82F6),
    'Postgraduate': Color(0xFF6366F1),
    'Diploma': Color(0xFF14B8A6),
    'Certificate': Color(0xFF22C55E),
    'Short Course': Color(0xFFF59E0B),
    // Intake
    'Fall': Color(0xFFFF6B35),
    'Spring': Color(0xFF22C55E),
    'Summer': Color(0xFFF59E0B),
    'Rolling': Color(0xFF6366F1),
    // Contract
    'Permanent': Color(0xFF3B82F6),
    'Contract': Color(0xFF6366F1),
    'Temporary': Color(0xFFF59E0B),
    'Sponsorship Available': Color(0xFF22C55E),
    // Trade
    'Import': Color(0xFF3B82F6),
    'Export': Color(0xFF22C55E),
    'Both': Color(0xFF6366F1),
    'Bulk': Color(0xFF8B5CF6),
    // Relocation
    'Housing': Color(0xFF3B82F6),
    'Banking': Color(0xFF10B981),
    'Schools': Color(0xFF8B5CF6),
    'Moving': Color(0xFF6366F1),
    // NRI
    'Tax Filing': Color(0xFF3B82F6),
    'Property Management': Color(0xFF6366F1),
    'Power of Attorney': Color(0xFF78716C),
    'Bank Account': Color(0xFF10B981),
    'Insurance': Color(0xFF22C55E),
    'Repatriation': Color(0xFF0EA5E9),
    // Gender
    'Male': Color(0xFF3B82F6),
    'Female': Color(0xFFEC4899),
    'Non-binary': Color(0xFF8B5CF6),
    'Other': Color(0xFF14B8A6),
    // ── Category Filter Option Colors ──
    // Experience Level
    'Entry Level': Color(0xFF22C55E),
    'Mid Level': Color(0xFF3B82F6),
    'Senior': Color(0xFF8B5CF6),
    'Intern': Color(0xFFF59E0B),
    // Employment Type
    'Full-Time': Color(0xFF3B82F6),
    'Part-Time': Color(0xFF6366F1),
    'Freelance': Color(0xFF14B8A6),
    'Internship': Color(0xFFF59E0B),
    // Work Mode
    'On-Site': Color(0xFF3B82F6),
    'Remote': Color(0xFF22C55E),
    // Industry (extra)
    'Media': Color(0xFFEC4899),
    'Government': Color(0xFF64748B),
    // Business Stage
    'Idea Stage': Color(0xFFF59E0B),
    'Pre-Revenue': Color(0xFF6366F1),
    'Early Revenue': Color(0xFF22C55E),
    'Growth Stage': Color(0xFF3B82F6),
    'Established': Color(0xFF8B5CF6),
    'Scaling': Color(0xFFEF4444),
    // Company Size
    '2-10': Color(0xFF22C55E),
    '11-50': Color(0xFF3B82F6),
    '51-200': Color(0xFF6366F1),
    '201-1000': Color(0xFF8B5CF6),
    '1000+': Color(0xFFD946EF),
    // Business Model
    'B2B': Color(0xFF3B82F6),
    'B2C': Color(0xFF22C55E),
    'Marketplace': Color(0xFF6366F1),
    'Subscription': Color(0xFF14B8A6),
    // Industry Sector (extra)
    'F&B': Color(0xFFEF4444),
    'Services': Color(0xFF0EA5E9),
    'Logistics': Color(0xFF64748B),
    // Social Availability
    'Now': Color(0xFFEF4444),
    'Today': Color(0xFF3B82F6),
    'This Week': Color(0xFF6366F1),
    'This Weekend': Color(0xFF22C55E),
    // Social Interests
    'Music': Color(0xFFEC4899),
    'Art': Color(0xFFA855F7),
    'Reading': Color(0xFF6366F1),
    'Gaming': Color(0xFF8B5CF6),
    'Movies': Color(0xFFEF4444),
    'Cooking': Color(0xFFFF6B35),
    // Vibes
    'Chill': Color(0xFF0EA5E9),
    'Energetic': Color(0xFFEF4444),
    'Intellectual': Color(0xFF6366F1),
    'Adventurous': Color(0xFF22C55E),
    // Educational Formats
    'In-Person': Color(0xFF3B82F6),
    'Online Live': Color(0xFF22C55E),
    'Self-Paced': Color(0xFFF59E0B),
    // Educational Subjects
    'Mathematics': Color(0xFF3B82F6),
    'Languages': Color(0xFF6366F1),
    'Programming': Color(0xFF14B8A6),
    'Test Prep': Color(0xFFEF4444),
    // Skill Level (extra)
    'Intermediate': Color(0xFF3B82F6),
    'Advanced': Color(0xFF6366F1),
    'Expert': Color(0xFFD946EF),
    // Creative Collaboration
    'Hobbyist': Color(0xFF22C55E),
    'Hire Me': Color(0xFF3B82F6),
    'Looking to Hire': Color(0xFF6366F1),
    'Collaborate': Color(0xFF14B8A6),
    'Learn Together': Color(0xFFF59E0B),
    'Mentor/Mentee': Color(0xFF8B5CF6),
    'Has Portfolio': Color(0xFF22C55E),
    'No Portfolio': Color(0xFF64748B),
    // Tech Experience Level
    'Junior (0-2 yr)': Color(0xFF22C55E),
    'Mid (2-5 yr)': Color(0xFF3B82F6),
    'Senior (5-10 yr)': Color(0xFF8B5CF6),
    'Lead/Architect (10+ yr)': Color(0xFFD946EF),
    // Tech Stack (extra)
    'TypeScript': Color(0xFF3178C6),
    'C++': Color(0xFF00599C),
    'Go': Color(0xFF00ADD8),
    'Rust': Color(0xFFDEA584),
    'Kotlin': Color(0xFF7F52FF),
    'Dart': Color(0xFF0175C2),
    // Tech Purpose
    'Hire': Color(0xFF3B82F6),
    'Get Hired': Color(0xFF22C55E),
    'Learn': Color(0xFFF59E0B),
    'Mentor': Color(0xFF8B5CF6),
    'Open Source': Color(0xFF14B8A6),
    // Industry Roles
    'Manufacturer': Color(0xFF64748B),
    'Supplier': Color(0xFF3B82F6),
    'Distributor': Color(0xFF6366F1),
    'Buyer': Color(0xFF22C55E),
    'Consultant': Color(0xFF8B5CF6),
    'Service Provider': Color(0xFF14B8A6),
    // Industry Company Size
    'Micro (1-10)': Color(0xFF22C55E),
    'Small (11-50)': Color(0xFF3B82F6),
    'Medium (51-200)': Color(0xFF6366F1),
    'Large (201-1000)': Color(0xFF8B5CF6),
    'Enterprise (1000+)': Color(0xFFD946EF),
    // Trade Type
    'Local': Color(0xFF22C55E),
    'National': Color(0xFF3B82F6),
    'International': Color(0xFF6366F1),
    // Certifications
    'ISO 9001': Color(0xFF3B82F6),
    'ISO 14001': Color(0xFF22C55E),
    'GMP': Color(0xFF6366F1),
    'HACCP': Color(0xFFF59E0B),
    'CE': Color(0xFF0EA5E9),
    'FDA': Color(0xFFEF4444),
    'BIS': Color(0xFF8B5CF6),
    // Risk Appetite
    'Conservative': Color(0xFF22C55E),
    'Moderate': Color(0xFF3B82F6),
    'Aggressive': Color(0xFFF59E0B),
    'Very Aggressive': Color(0xFFEF4444),
    // Investment Horizon
    'Short-Term (< 1yr)': Color(0xFFF59E0B),
    'Medium (1-3yr)': Color(0xFF3B82F6),
    'Long-Term (3-10yr)': Color(0xFF6366F1),
    'Very Long (10+yr)': Color(0xFF8B5CF6),
    // Investment Purpose
    'Invest': Color(0xFF22C55E),
    'Raise Capital': Color(0xFFEF4444),
    'Advise': Color(0xFF6366F1),
    'Partner': Color(0xFF14B8A6),
    // Event Format
    'Online': Color(0xFF22C55E),
    // Event When
    'This Month': Color(0xFF6366F1),
    // Time of Day
    'Morning': Color(0xFFF59E0B),
    'Afternoon': Color(0xFF3B82F6),
    'Evening': Color(0xFF6366F1),
    'Night': Color(0xFF1E293B),
    // Event Price
    'Free': Color(0xFF22C55E),
    'Paid': Color(0xFF3B82F6),
    // Community Involvement
    'Donate': Color(0xFFEC4899),
    'Organize': Color(0xFF3B82F6),
    'Advocate': Color(0xFFEF4444),
    // Commitment
    'One-Time': Color(0xFF3B82F6),
    'Weekly': Color(0xFF22C55E),
    'Monthly': Color(0xFF6366F1),
    'Ongoing': Color(0xFF8B5CF6),
    'Seasonal': Color(0xFF14B8A6),
    // Cause Area
    'Environment': Color(0xFF22C55E),
    'Poverty': Color(0xFFF59E0B),
    'Human Rights': Color(0xFF6366F1),
    'Animals': Color(0xFFEC4899),
    'Arts & Culture': Color(0xFFA855F7),
    // Skills Offered
    'Teaching': Color(0xFF3B82F6),
    'Medical': Color(0xFFEF4444),
    'Technical': Color(0xFF64748B),
    'Fundraising': Color(0xFF22C55E),
    'Counseling': Color(0xFF8B5CF6),
    'Creative': Color(0xFFEC4899),
    // Personal Development Format
    'Group': Color(0xFF3B82F6),
    '1-on-1': Color(0xFF6366F1),
    // Session Duration
    '15 min': Color(0xFF22C55E),
    '30 min': Color(0xFF3B82F6),
    '45 min': Color(0xFF6366F1),
    '1 hr': Color(0xFF8B5CF6),
    '2 hr': Color(0xFFD946EF),
    // Goals (extra)
    'Stress Relief': Color(0xFF14B8A6),
    'Focus': Color(0xFF3B82F6),
    // Global Destinations
    'USA': Color(0xFF3B82F6),
    'Canada': Color(0xFFEF4444),
    'UK': Color(0xFF1E293B),
    'Australia': Color(0xFFF59E0B),
    'UAE': Color(0xFF22C55E),
    'Singapore': Color(0xFFEF4444),
    'New Zealand': Color(0xFF14B8A6),
    // Service Type
    'Consultation': Color(0xFF3B82F6),
    'Documentation': Color(0xFF6366F1),
    'Representation': Color(0xFF8B5CF6),
    'Guidance': Color(0xFF22C55E),
    'Community': Color(0xFF14B8A6),
    // Urgency
    'Immediate': Color(0xFFEF4444),
    'Within 1 Month': Color(0xFFF59E0B),
    'Within 3 Months': Color(0xFF3B82F6),
    'Within 6 Months': Color(0xFF6366F1),
    'Planning Ahead': Color(0xFF22C55E),
    // Indian Languages
    'Gujarati': Color(0xFFFF6B35),
    'Punjabi': Color(0xFFF59E0B),
    'Tamil': Color(0xFFEF4444),
    'Telugu': Color(0xFF3B82F6),
    'Bengali': Color(0xFF22C55E),
    'Marathi': Color(0xFF6366F1),
  };

  // ── Subcategory-Specific Filters ──
  static const Map<String, List<Map<String, dynamic>>> subcategoryFilters = {
    // Professional
    'Job Seekers': [
      {
        'label': 'Education',
        'type': 'dropdown',
        'options': [
          'High School',
          'Associate',
          "Bachelor's",
          "Master's",
          'PhD',
          'Self-Taught',
        ],
      },
    ],
    'Freelancers': [
      {
        'label': 'Project Type',
        'type': 'dropdown',
        'options': ['Hourly', 'Fixed-Price', 'Retainer', 'Equity'],
      },
    ],
    'Consultants': [
      {
        'label': 'Specialty',
        'type': 'dropdown',
        'options': [
          'Strategy',
          'Operations',
          'Finance',
          'Marketing',
          'HR',
          'IT',
          'Legal',
          'Other',
        ],
      },
    ],
    'Remote Workers': [
      {
        'label': 'Time Zone',
        'type': 'dropdown',
        'options': [
          'IST (UTC+5:30)',
          'EST (UTC-5)',
          'PST (UTC-8)',
          'GMT (UTC+0)',
          'CET (UTC+1)',
          'AEST (UTC+10)',
          'JST (UTC+9)',
        ],
      },
    ],
    'Recruiters': [
      {
        'label': 'Hiring For',
        'type': 'dropdown',
        'options': [
          'Tech',
          'Sales',
          'Marketing',
          'Design',
          'Operations',
          'Finance',
          'HR',
          'Executive',
        ],
      },
    ],
    // Business
    'Startup Founders': [
      {
        'label': 'Funding Stage',
        'type': 'dropdown',
        'options': [
          'Bootstrapped',
          'Pre-Seed',
          'Seed',
          'Series A',
          'Series B',
          'Series C+',
        ],
      },
    ],
    'Investors': [
      {
        'label': 'Investment Type',
        'type': 'dropdown',
        'options': ['Angel', 'VC', 'PE', 'Debt', 'Crypto'],
      },
      {
        'label': 'Preferred Stage',
        'type': 'dropdown',
        'options': [
          'Pre-Seed',
          'Seed',
          'Series A',
          'Series B',
          'Series C+',
          'Growth',
        ],
      },
    ],
    'E-commerce': [
      {
        'label': 'Platform',
        'type': 'dropdown',
        'options': [
          'Shopify',
          'Amazon',
          'WooCommerce',
          'Custom',
          'Multi-Platform',
        ],
      },
    ],
    'Franchise': [
      {
        'label': 'Franchise Type',
        'type': 'dropdown',
        'options': ['Food', 'Retail', 'Service', 'Education', 'Fitness'],
      },
    ],
    // Social
    'Dating': [
      {
        'label': 'Relationship Goal',
        'type': 'dropdown',
        'options': ['Serious', 'Casual', 'Open to Anything'],
      },
      {
        'label': 'Lifestyle',
        'type': 'dropdown',
        'options': [
          'Non-Smoker',
          'Social Drinker',
          'Vegetarian',
          'Fitness Lover',
          'Pet Lover',
        ],
      },
    ],
    'Travel Companions': [
      {
        'label': 'Travel Style',
        'type': 'dropdown',
        'options': ['Budget', 'Mid-Range', 'Luxury', 'Backpacking'],
      },
      {
        'label': 'Trip Duration',
        'type': 'dropdown',
        'options': ['Weekend', '1 Week', '2+ Weeks', 'Long-Term'],
      },
    ],
    'Roommates': [
      {
        'label': 'Lifestyle',
        'type': 'dropdown',
        'options': [
          'Early Bird',
          'Night Owl',
          'Pet-Friendly',
          'Vegetarian',
          'Non-Smoker',
          'Quiet',
        ],
      },
    ],
    'Party Buddies': [
      {
        'label': 'Scene',
        'type': 'dropdown',
        'options': ['Clubs', 'Bars', 'House Parties', 'Live Music', 'Rooftops'],
      },
      {
        'label': 'Music Taste',
        'type': 'dropdown',
        'options': ['EDM', 'Hip-Hop', 'Bollywood', 'Rock', 'Pop', 'Jazz'],
      },
    ],
    // Educational
    'Exam Prep': [
      {
        'label': 'Exam Type',
        'type': 'dropdown',
        'options': [
          'SAT',
          'GRE',
          'GMAT',
          'IELTS',
          'TOEFL',
          'UPSC',
          'CAT',
          'JEE',
          'NEET',
          'Other',
        ],
      },
    ],
    'Language Learning': [
      {
        'label': 'Target Language',
        'type': 'dropdown',
        'options': [
          'English',
          'Spanish',
          'French',
          'German',
          'Mandarin',
          'Japanese',
          'Korean',
          'Arabic',
          'Hindi',
          'Other',
        ],
      },
      {
        'label': 'Proficiency',
        'type': 'dropdown',
        'options': [
          'A1 (Beginner)',
          'A2 (Elementary)',
          'B1 (Intermediate)',
          'B2 (Upper Intermediate)',
          'C1 (Advanced)',
          'C2 (Fluent)',
        ],
      },
    ],
    'Coding Bootcamp': [
      {
        'label': 'Tech Stack',
        'type': 'dropdown',
        'options': [
          'Python',
          'JavaScript',
          'React',
          'Node.js',
          'Flutter',
          'AI/ML',
          'Java',
          'Swift',
        ],
      },
      {
        'label': 'Duration',
        'type': 'dropdown',
        'options': ['4 Weeks', '8 Weeks', '12 Weeks', '6 Months'],
      },
    ],
    'Study Groups': [
      {
        'label': 'Group Size',
        'type': 'dropdown',
        'options': ['2-3', '4-6', '7-10', '10+'],
      },
    ],
    // Creative
    'Photography': [
      {
        'label': 'Style',
        'type': 'dropdown',
        'options': [
          'Portrait',
          'Landscape',
          'Wedding',
          'Product',
          'Street',
          'Fashion',
          'Food',
          'Drone',
        ],
      },
    ],
    'Graphic Design': [
      {
        'label': 'Specialty',
        'type': 'dropdown',
        'options': [
          'Logo',
          'Branding',
          'UI/UX',
          'Print',
          'Packaging',
          'Social Media',
          'Illustration',
        ],
      },
    ],
    'Music Production': [
      {
        'label': 'Genre',
        'type': 'dropdown',
        'options': [
          'Pop',
          'Hip-Hop',
          'EDM',
          'Classical',
          'Rock',
          'Bollywood',
          'Jazz',
          'Lo-Fi',
        ],
      },
      {
        'label': 'Service',
        'type': 'dropdown',
        'options': [
          'Mixing',
          'Mastering',
          'Beat Making',
          'Composition',
          'Sound Design',
        ],
      },
    ],
    'Film Making': [
      {
        'label': 'Type',
        'type': 'dropdown',
        'options': [
          'Short Film',
          'Documentary',
          'Commercial',
          'Music Video',
          'Corporate',
          'Wedding',
        ],
      },
      {
        'label': 'Role Needed',
        'type': 'dropdown',
        'options': [
          'Director',
          'Editor',
          'Cinematographer',
          'Actor',
          'Sound',
          'VFX',
        ],
      },
    ],
    'Content Creation': [
      {
        'label': 'Platform',
        'type': 'dropdown',
        'options': [
          'YouTube',
          'Instagram',
          'TikTok',
          'Podcast',
          'Blog',
          'LinkedIn',
        ],
      },
      {
        'label': 'Content Type',
        'type': 'dropdown',
        'options': ['Video', 'Photo', 'Written', 'Audio', 'Mixed Media'],
      },
    ],
    'Writing & Blogging': [
      {
        'label': 'Niche',
        'type': 'dropdown',
        'options': [
          'Tech',
          'Lifestyle',
          'Travel',
          'Finance',
          'Health',
          'Food',
          'Fiction',
          'Copywriting',
        ],
      },
    ],
    // Tech
    'Software Development': [
      {
        'label': 'Domain',
        'type': 'dropdown',
        'options': ['Backend', 'Frontend', 'Full-Stack', 'Embedded', 'Systems'],
      },
    ],
    'Mobile Apps': [
      {
        'label': 'Platform',
        'type': 'dropdown',
        'options': [
          'iOS',
          'Android',
          'Cross-Platform',
          'Flutter',
          'React Native',
        ],
      },
    ],
    'AI & Machine Learning': [
      {
        'label': 'Subfield',
        'type': 'dropdown',
        'options': [
          'NLP',
          'Computer Vision',
          'Deep Learning',
          'Generative AI',
          'MLOps',
          'Reinforcement Learning',
        ],
      },
    ],
    'Cybersecurity': [
      {
        'label': 'Focus',
        'type': 'dropdown',
        'options': [
          'Pen Testing',
          'Security Audit',
          'Compliance',
          'Incident Response',
          'SOC',
          'GRC',
        ],
      },
    ],
    'Cloud Computing': [
      {
        'label': 'Cloud Platform',
        'type': 'dropdown',
        'options': ['AWS', 'Azure', 'GCP', 'Multi-Cloud'],
      },
    ],
    'Data Science': [
      {
        'label': 'Tools',
        'type': 'dropdown',
        'options': ['Python', 'R', 'SQL', 'Tableau', 'Power BI', 'Spark'],
      },
    ],
    'Blockchain': [
      {
        'label': 'Chain',
        'type': 'dropdown',
        'options': ['Ethereum', 'Solana', 'Bitcoin', 'Polygon', 'Polkadot'],
      },
      {
        'label': 'Focus',
        'type': 'dropdown',
        'options': ['Smart Contracts', 'DeFi', 'NFT', 'DApp', 'Web3'],
      },
    ],
    'UI/UX Design': [
      {
        'label': 'Tools',
        'type': 'dropdown',
        'options': ['Figma', 'Sketch', 'Adobe XD', 'Framer', 'InVision'],
      },
    ],
    // Industry
    'Manufacturing': [
      {
        'label': 'Capacity',
        'type': 'dropdown',
        'options': ['Small Batch', 'Medium', 'Large Scale', 'Mass Production'],
      },
    ],
    'Construction': [
      {
        'label': 'Project Type',
        'type': 'dropdown',
        'options': [
          'Residential',
          'Commercial',
          'Infrastructure',
          'Industrial',
          'Renovation',
        ],
      },
    ],
    'Real Estate': [
      {
        'label': 'Property Type',
        'type': 'dropdown',
        'options': [
          'Residential',
          'Commercial',
          'Industrial',
          'Land',
          'Co-Working',
        ],
      },
      {
        'label': 'Transaction',
        'type': 'dropdown',
        'options': ['Buy', 'Sell', 'Rent', 'Lease'],
      },
    ],
    'Agriculture': [
      {
        'label': 'Product',
        'type': 'dropdown',
        'options': [
          'Crops',
          'Livestock',
          'Dairy',
          'Poultry',
          'Aquaculture',
          'Organic',
          'AgriTech',
        ],
      },
    ],
    'Automotive': [
      {
        'label': 'Segment',
        'type': 'dropdown',
        'options': [
          'Passenger',
          'Commercial',
          'Two-Wheeler',
          'EV',
          'Parts',
          'Service',
        ],
      },
    ],
    'Pharmaceuticals': [
      {
        'label': 'Type',
        'type': 'dropdown',
        'options': ['Generic', 'Branded', 'API', 'Biotech', 'Medical Devices'],
      },
    ],
    'Food Processing': [
      {
        'label': 'Category',
        'type': 'dropdown',
        'options': [
          'Dairy',
          'Bakery',
          'Beverages',
          'Frozen',
          'Snacks',
          'Spices',
          'Organic',
        ],
      },
    ],
    // Investment & Finance
    'Stock Market': [
      {
        'label': 'Sector',
        'type': 'dropdown',
        'options': [
          'Technology',
          'Healthcare',
          'Finance',
          'Energy',
          'Consumer',
          'Industrial',
          'Real Estate',
        ],
      },
      {
        'label': 'Market Cap',
        'type': 'dropdown',
        'options': ['Micro', 'Small', 'Mid', 'Large', 'Mega'],
      },
    ],
    'Cryptocurrency': [
      {
        'label': 'Token Type',
        'type': 'dropdown',
        'options': ['Layer 1', 'Layer 2', 'DeFi', 'NFT', 'Stablecoin', 'Meme'],
      },
    ],
    'Mutual Funds': [
      {
        'label': 'Fund Type',
        'type': 'dropdown',
        'options': ['Equity', 'Debt', 'Hybrid', 'Index', 'ELSS', 'Liquid'],
      },
    ],
    'Angel Investing': [
      {
        'label': 'Preferred Sector',
        'type': 'dropdown',
        'options': [
          'Tech',
          'Healthcare',
          'FinTech',
          'EdTech',
          'D2C',
          'SaaS',
          'AgriTech',
        ],
      },
    ],
    'Venture Capital': [
      {
        'label': 'Preferred Stage',
        'type': 'dropdown',
        'options': ['Pre-Seed', 'Seed', 'Series A', 'Series B', 'Series C+'],
      },
    ],
    'Financial Planning': [
      {
        'label': 'Goal',
        'type': 'dropdown',
        'options': [
          'Retirement',
          'Education',
          'Wealth Building',
          'Tax Saving',
          'Emergency Fund',
          'Debt Payoff',
        ],
      },
    ],
    // Event & Meetup
    'Hackathons': [
      {
        'label': 'Theme',
        'type': 'dropdown',
        'options': [
          'AI',
          'Web3',
          'FinTech',
          'HealthTech',
          'Social Good',
          'Open',
        ],
      },
      {
        'label': 'Team Size',
        'type': 'dropdown',
        'options': ['Solo', '2-3', '4-5', 'Open'],
      },
    ],
    'Conferences': [
      {
        'label': 'Audience',
        'type': 'dropdown',
        'options': ['Beginner', 'Professional', 'Executive', 'Academic'],
      },
    ],
    'Sports Events': [
      {
        'label': 'Sport',
        'type': 'dropdown',
        'options': [
          'Cricket',
          'Football',
          'Tennis',
          'Running',
          'Cycling',
          'Swimming',
          'Martial Arts',
          'Other',
        ],
      },
      {
        'label': 'Participation',
        'type': 'dropdown',
        'options': ['Participate', 'Spectate', 'Volunteer'],
      },
    ],
    'Concerts & Music': [
      {
        'label': 'Genre',
        'type': 'dropdown',
        'options': [
          'Pop',
          'Rock',
          'Classical',
          'EDM',
          'Hip-Hop',
          'Bollywood',
          'Jazz',
          'Indie',
        ],
      },
    ],
    // Community
    'Volunteering': [
      {
        'label': 'Availability',
        'type': 'dropdown',
        'options': ['Weekdays', 'Weekends', 'Evenings', 'Flexible'],
      },
    ],
    'Environmental': [
      {
        'label': 'Focus',
        'type': 'dropdown',
        'options': [
          'Climate',
          'Conservation',
          'Recycling',
          'Clean Energy',
          'Water',
          'Reforestation',
          'Wildlife',
        ],
      },
    ],
    'Animal Welfare': [
      {
        'label': 'Animal Type',
        'type': 'dropdown',
        'options': [
          'Dogs',
          'Cats',
          'Farm Animals',
          'Wildlife',
          'Marine',
          'Birds',
          'All',
        ],
      },
    ],
    'Women Empowerment': [
      {
        'label': 'Focus',
        'type': 'dropdown',
        'options': [
          'Education',
          'Employment',
          'Safety',
          'Health',
          'Legal Rights',
          'Leadership',
          'Financial',
        ],
      },
    ],
    'Youth Development': [
      {
        'label': 'Age Group',
        'type': 'dropdown',
        'options': ['6-10', '11-14', '15-18', '18-25'],
      },
      {
        'label': 'Program Type',
        'type': 'dropdown',
        'options': [
          'Sports',
          'STEM',
          'Arts',
          'Leadership',
          'Career',
          'Life Skills',
        ],
      },
    ],
    // Personal Development
    'Fitness & Gym': [
      {
        'label': 'Workout Type',
        'type': 'dropdown',
        'options': [
          'Strength',
          'Cardio',
          'CrossFit',
          'HIIT',
          'Calisthenics',
          'Functional',
        ],
      },
      {
        'label': 'Fitness Goal',
        'type': 'dropdown',
        'options': [
          'Weight Loss',
          'Muscle Gain',
          'Endurance',
          'Flexibility',
          'General Fitness',
        ],
      },
    ],
    'Meditation & Yoga': [
      {
        'label': 'Style',
        'type': 'dropdown',
        'options': [
          'Hatha',
          'Vinyasa',
          'Ashtanga',
          'Kundalini',
          'Guided Meditation',
          'Breathwork',
        ],
      },
    ],
    'Public Speaking': [
      {
        'label': 'Context',
        'type': 'dropdown',
        'options': [
          'Professional',
          'TED-Style',
          'Debate',
          'Toastmasters',
          'Storytelling',
          'Sales',
        ],
      },
    ],
    'Life Coaching': [
      {
        'label': 'Specialty',
        'type': 'dropdown',
        'options': [
          'Career',
          'Relationships',
          'Health',
          'Finance',
          'Confidence',
          'Executive',
        ],
      },
    ],
    'Book Club': [
      {
        'label': 'Genre',
        'type': 'dropdown',
        'options': [
          'Self-Help',
          'Business',
          'Fiction',
          'Science',
          'Philosophy',
          'Biography',
          'Psychology',
        ],
      },
      {
        'label': 'Pace',
        'type': 'dropdown',
        'options': ['1 Chapter/Week', 'Whole Book', 'Audio + Discussion'],
      },
    ],
    // Global / NRI
    'Immigration': [
      {
        'label': 'Visa Category',
        'type': 'dropdown',
        'options': [
          'Work Visa',
          'Family Visa',
          'Investor Visa',
          'Permanent Residence',
          'Citizenship',
          'Asylum',
        ],
      },
    ],
    'Study Abroad': [
      {
        'label': 'Degree Level',
        'type': 'dropdown',
        'options': [
          'Undergraduate',
          'Postgraduate',
          'PhD',
          'Diploma',
          'Certificate',
          'Short Course',
        ],
      },
      {
        'label': 'Intake',
        'type': 'dropdown',
        'options': ['Fall', 'Spring', 'Summer', 'Rolling'],
      },
    ],
    'Overseas Jobs': [
      {
        'label': 'Contract Type',
        'type': 'dropdown',
        'options': [
          'Permanent',
          'Contract',
          'Temporary',
          'Sponsorship Available',
        ],
      },
    ],
    'International Trade': [
      {
        'label': 'Direction',
        'type': 'dropdown',
        'options': ['Import', 'Export', 'Both'],
      },
      {
        'label': 'Volume',
        'type': 'dropdown',
        'options': ['Small', 'Medium', 'Large', 'Bulk'],
      },
    ],
    'Relocation Help': [
      {
        'label': 'Service Needed',
        'type': 'dropdown',
        'options': [
          'Housing',
          'Banking',
          'Schools',
          'Healthcare',
          'Legal',
          'Moving',
        ],
      },
    ],
    'NRI Services': [
      {
        'label': 'Service',
        'type': 'dropdown',
        'options': [
          'Tax Filing',
          'Property Management',
          'Power of Attorney',
          'Bank Account',
          'Insurance',
          'Repatriation',
        ],
      },
    ],
  };

  // ── Helpers ──

  /// Get gradient color pair for a category, with fallback.
  static List<Color> getCategoryColors(String? category) {
    return categoryColors[category] ??
        const [Color(0xFF6366F1), Color(0xFF818CF8)];
  }

  /// Get icon for a category (rounded variant), with fallback.
  static IconData getCategoryIcon(String? category) {
    return categoryIcons[category] ?? Icons.hub_rounded;
  }

  /// Get flat color for a category (Live Connect variant), with fallback.
  static Color getCategoryFlatColor(String? category) {
    return categoryFlatColors[category] ?? const Color(0xFF2196F3);
  }
}
