// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
        apiKey: dotenv.env['FIREBASE_WEB_API_KEY'] ?? '',
        authDomain: dotenv.env['FIREBASE_WEB_AUTH_DOMAIN'] ?? '',
        projectId: dotenv.env['FIREBASE_WEB_PROJECT_ID'] ?? '',
        storageBucket: dotenv.env['FIREBASE_WEB_STORAGE_BUCKET'] ?? '',
        messagingSenderId: dotenv.env['FIREBASE_WEB_MESSAGING_SENDER_ID'] ?? '',
        appId: dotenv.env['FIREBASE_WEB_APP_ID'] ?? '',
      );

  static FirebaseOptions get android => FirebaseOptions(
        apiKey: dotenv.env['FIREBASE_ANDROID_API_KEY'] ?? '',
        appId: dotenv.env['FIREBASE_ANDROID_APP_ID'] ?? '',
        messagingSenderId: dotenv.env['FIREBASE_WEB_MESSAGING_SENDER_ID'] ?? '',
        projectId: dotenv.env['FIREBASE_WEB_PROJECT_ID'] ?? '',
        storageBucket: dotenv.env['FIREBASE_WEB_STORAGE_BUCKET'] ?? '',
      );

  // Placeholder configurations for other platforms
  // These will use the same configuration as Android for now
  // You can update these when you add support for these platforms
  static FirebaseOptions get ios => FirebaseOptions(
        apiKey: dotenv.env['FIREBASE_IOS_API_KEY'] ?? '',
        appId: dotenv.env['FIREBASE_IOS_APP_ID'] ?? '',
        messagingSenderId: dotenv.env['FIREBASE_WEB_MESSAGING_SENDER_ID'] ?? '',
        projectId: dotenv.env['FIREBASE_WEB_PROJECT_ID'] ?? '',
        storageBucket: dotenv.env['FIREBASE_WEB_STORAGE_BUCKET'] ?? '',
        iosBundleId: dotenv.env['FIREBASE_IOS_BUNDLE_ID'] ?? '',
      );

  static FirebaseOptions get macos => FirebaseOptions(
        apiKey: dotenv.env['FIREBASE_IOS_API_KEY'] ?? '',
        appId: dotenv.env['FIREBASE_IOS_APP_ID'] ?? '',
        messagingSenderId: dotenv.env['FIREBASE_WEB_MESSAGING_SENDER_ID'] ?? '',
        projectId: dotenv.env['FIREBASE_WEB_PROJECT_ID'] ?? '',
        storageBucket: dotenv.env['FIREBASE_WEB_STORAGE_BUCKET'] ?? '',
        iosBundleId: dotenv.env['FIREBASE_IOS_BUNDLE_ID'] ?? '',
      );

  static FirebaseOptions get windows => FirebaseOptions(
        apiKey: dotenv.env['FIREBASE_ANDROID_API_KEY'] ?? '',
        appId: dotenv.env['FIREBASE_WEB_APP_ID'] ?? '',
        messagingSenderId: dotenv.env['FIREBASE_WEB_MESSAGING_SENDER_ID'] ?? '',
        projectId: dotenv.env['FIREBASE_WEB_PROJECT_ID'] ?? '',
        authDomain: dotenv.env['FIREBASE_WEB_AUTH_DOMAIN'] ?? '',
        storageBucket: dotenv.env['FIREBASE_WEB_STORAGE_BUCKET'] ?? '',
      );

  static FirebaseOptions get linux => FirebaseOptions(
        apiKey: dotenv.env['FIREBASE_ANDROID_API_KEY'] ?? '',
        appId: dotenv.env['FIREBASE_WEB_APP_ID'] ?? '',
        messagingSenderId: dotenv.env['FIREBASE_WEB_MESSAGING_SENDER_ID'] ?? '',
        projectId: dotenv.env['FIREBASE_WEB_PROJECT_ID'] ?? '',
        authDomain: dotenv.env['FIREBASE_WEB_AUTH_DOMAIN'] ?? '',
        storageBucket: dotenv.env['FIREBASE_WEB_STORAGE_BUCKET'] ?? '',
      );
}
